### ISSUE TITLE
Remove mid-function empty lines after a closing brace

### ISSUE THREAD

**Issue by karalabe** [mvdan/gofumpt#10]
This might be a bit opinionated, but here it goes anyway. I'm wondering whether it would make sense to **remove empty lines** after closing braces, if that is followed by further code. E.g.

```go
for i:=0; i<10; i++ {
    fmt.Println(i)
}

// This part will so something something
if err := doSomething(); err != nil {
    return err
}

if err := doSomethingElse(); err != nil {
    return err
}

// Everything done, dunno what next
```

vs.

```go
for i:=0; i<10; i++ {
    fmt.Println(i)
}
// This part will so something something
if err := doSomething(); err != nil {
    return err
}
if err := doSomethingElse(); err != nil {
    return err
}
// Everything done, dunno what next
```

IMHO, the first code falls apart. The closing brace line `}` (it's essentially an 99% empty line) already acts as a visual separator, so adding an extra empty line only further emphasizes that something else is happening. But this emphasis is imho not needed:

 * If the following code is a logical continuation, the extra empty line just breaks the visual flow.
 * If the following code is a completely different thing that warrants visual emphasis, a comment can help create both more readable code and also add the extra visual break to highlight it.

Now, the reason I'm asking for this to be considered in this tool is because this is one of those things that as a maintainer I'd like to enforce, but it's both painful and annoying for everyone to manually write this down on every PR at 25 different locations explaining why this is good. An automated tool could both clean up the repo automatically and also enforce in CI.

**Comment by karalabe** [comment]
E.g. Some live code from our repo that uses this style: https://github.com/ethereum/go-ethereum/blob/master/accounts/usbwallet/wallet.go#L443 Here I think any added new line would just make it harder to read.

**Comment by karalabe** [comment]
Oh, one more instance where I think this is useful. After a inline-defined goroutine launch without any parameters:

```go
go func() {
    // Do something
}()
noNeedForEmptyLineBeforeThis()
```

**Comment by mvdan** [comment]
Thanks for filing this issue. I mostly agree with the sentiment, but I worry that this would be too agressive as a rule. When separating chunks of code, I don't think a comment is always enough. It can be enough if the code is simple and short, and if you're used to that style, but in reality not much Go code follows that style.

For example, I opened a random file from the Go standard library, and found multiple instances that don't follow this style, like https://golang.org/src/testing/testing.go#L767. In that case, you'd force the author to either move or add a comment, and I don't think the result would be more readable or more consistent.

One of the driving forces in these rules is to enforce what 95% of idiomatic Go code already follows. While you can argue that this would be something useful for some projects, I think it's not something that's widespread or a net readability win (see above).

**Comment by mdlayher** [comment]
This is extraordinarily subjective and I don't think there's any consensus that this approach is better or more readable.

I personally find it maddening to try to read a function that is 100 lines long with absolutely no blank lines to break up logical pieces. Whitespace can and should be used to group logical blocks of functionality.

**Comment by karalabe** [comment]
> This is extraordinarily subjective and I don't think there's any consensus that this approach is better or more readable.

Hence why I wrote "opinionated" and "wondering".

> I personally find it maddening to try to read a function that is 100 lines long with absolutely no blank lines to break up logical pieces.

Apart from some extreme math heavy code, I don't think any program exists out there that is 100 lines long without a single `for` loop of `if` branch. If you do have those however, you already have empty lines on the closing braces.

I personally find it maddening to try to read a function that is 100 lines long with absolutely no ~~blank lines~~ comments to ~~break up~~ explain logical pieces.

**Comment by mvdan** [comment]
While gofumpt is even more opinionated than gofmt, it tries to follow the already-present standards. I think this is too ambitious and controversial for the tool. And I definitely don't want to add flags :)

@karalabe if you can come up with a rule or heuristic that would keep most existing idiomatic Go code intact, I'm happy to consider it. Otherwise, this is unlikely to happen right now.
