### ISSUE TITLE
gofumpt does not insert a space between // and http.

### ISSUE THREAD

**Issue by bokunodev** [mvdan/gofumpt#101]
gofumpt/gofumports treat `uri scheme` in comment as  ` go directive`.

**Comment by mvdan** [comment]
I don't understand. Please provide an example I can run.

**Comment by bokunodev** [comment]
gofumports treat `http://` in a comment like `go: directive`
i wonder, is this by design ? 

https://user-images.githubusercontent.com/54968427/103179782-06cebf00-48c2-11eb-8191-e3a24f8fdfbc.mp4

**Comment by mvdan** [comment]
Thanks, thinking that URLs are Go comment directives was not intentional.
