### ISSUE TITLE
README: go get on executables is deprecated

### ISSUE THREAD

**Issue by slimsag** [mvdan/gofumpt#102]
The README suggests:

```
GO111MODULE=on go get mvdan.cc/gofumpt
```

But with the latest Go 1.15 this gives deprecation warnings:

```
$ go get mvdan.cc/gofumpt
go: downloading mvdan.cc/gofumpt v0.0.0-20201217210418-dbaa36cfdf8e
go: downloading github.com/google/go-cmp v0.5.3
go: downloading golang.org/x/tools v0.0.0-20201121010211-780cb80bd7fb
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	See 'go help get' and 'go help install' for more information.
```

Strangely (perhaps my misunderstanding?) `go install` does not work on this package outside of a directory with a `go.mod` file:

```
$ go install mvdan.cc/gofumpt
no required module provides package mvdan.cc/gofumpt: working directory is not part of a module
```

I also note this repository doesn't have any tagged releases - perhaps that could be the cause?

Not sure when you want to adopt the new `go install` command, but thought it worth mentioning. Thanks for the great tool!

**Comment by mvdan** [comment]
I think you mean one of the 1.16 pre-releases. See https://github.com/mvdan/gofumpt/issues/94, which sparked raising an issue in upstream Go, and the deprecation notice was removed from 1.16. I think it was already gone from beta1, but if not, it definitely will be from rc1. See https://github.com/golang/go/issues/42885.

**Comment by mvdan** [comment]
To clarify - I will update the READMEs to use the new `go install` once Go 1.17 is out, because then we'll drop support for Go 1.15, the last version to not support the new `go install`.

**Comment by slimsag** [comment]
Thanks! And yes, you are correct - I somehow was running a non-release Go version by accident
