### ISSUE TITLE
Remove whitespace and newline from `interface{}` types

### ISSUE THREAD

**Issue by slimsag** [mvdan/gofumpt#103]
Using both the latest `master` revision dbaa36cf, and the latest `break-long-lines` branch 8be3105e of gofumpt, the following is considered formatted:

```Go
package main

func main() {
	v := []interface {
	}{1, 2, 3}
	_ = v
}
```

I would expect `interface {` to have no space in it, and no newline after it. e.g. I expect something like:

```Go
package main

func main() {
	v := []interface{}{1, 2, 3}
	_ = v
}
```

Datapoints: A search over the golang/go codebase [shows 2902 usages of `interface{}`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/golang/go%24+count:99999+file:%5C.go%24+interface%7B%7D&patternType=regexp) with no whitespace or newlines, only [38 usages of `interface {}` with a space](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/golang/go%24+count:99999+file:%5C.go%24+interface%5Cs%2B%7B%7D&patternType=regexp), and only 14 usages of [`interface{}` with a newline between the braces](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/golang/go%24+count:99999+file:%5C.go%24+interface%5Cs*%7B%5Cn%7D&patternType=regexp).

This occurs most frequently in generated Go code (I discovered this when using gofumpt for https://github.com/hexops/valast).

**Comment by mvdan** [comment]
I agree that this makes sense, and we should do it for empty structs too. If the author wants the elements to be on the second line, they can add a newline right before the first element.

**Comment by mvdan** [comment]
Let me know how it works for you - I ran it on multiple codebases I maintain, and it had zero changes, which is a good sign. A few changes showed up for other projects I tried it on, and they all made sense to me.

**Comment by slimsag** [comment]
Oh slick, you rock @mvdan ! I'll report back very soon :)

**Comment by slimsag** [comment]
[I can confirm](https://github.com/hexops/valast/pull/4) this works really well 🎉 Thank you a ton!!
