### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by svyotov** [mvdan/gofumpt#107]
The certificate for [mvdan.cc/gofumpt](https://mvdan.cc/gofumpt) has expired.
```sh
> GO111MODULE=on go get mvdan.cc/gofumpt
go get mvdan.cc/gofumpt: unrecognized import path "mvdan.cc/gofumpt": https fetch: Get "https://mvdan.cc/gofumpt?go-get=1": x509: certificate has expired or is not yet valid: current time 2021-01-06T11:46:16Z is after 2021-01-06T11:32:18Z
```

**Comment by mvdan** [comment]
Thanks, this is fixed now.

Why is this causing so many problems, though? I thought that proxy.golang.org would shield from this.

**Comment by mvdan** [comment]
Also, did any of you disable the proxy by any chance?

**Comment by tombuildsstuff** [comment]
@mvdan in our instance we didn't try disabling the proxy - but we should be bypassing it since `GO111MODULE` was set to `off` (to install as a global tool)

**Comment by mvdan** [comment]
Gotcha. Once Go 1.16 is out, you'll be able to do that with module mode enabled, via `go get mvdan.cc/gofumpt@latest`. That will use the proxy too, so it will be faster and more reliable.
