### ISSUE TITLE
Order of imports

### ISSUE THREAD

**Issue by rekkerz** [mvdan/gofumpt#113]
My coworkers work in IntelliJ with gofmt formatting.
One of the things I've noticed is the order of imports is altered which doesn't look great on merge requests.

**Example:**
_Original:_
> import (
	"gitlab.xxx.com/xxx/xxx/xxx/xxx"
	"gitlab.yyy.com/xxx/xxx/xxx/xxx/xxx"
	"gitlab.zzz.com/xxx/xxx/xxx/xxx"
	"testing"
)

_Mine (after I hit save):_
> import (
	"testing"
	"gitlab.xxx.com/xxx/xxx/xxx/xxx"
	"gitlab.yyy.com/xxx/xxx/xxx/xxx/xxx"
	"gitlab.zzz.com/xxx/xxx/xxx/xxx"
)

As you can see the order of internal imports remains the same while the external imports (testing) changes.

It would be awesome if there was a flag that allows you to change this behavior.

**Comment by mvdan** [comment]
Are you using gofumpt? If so, please provide a Go file where I can reproduce the issue with gofumpt.

**Comment by rekkerz** [comment]
Yes I am using gofumpts.

So gofmt uses alphabetical sorting of packages.
Consider this example (you can just copy-paste to replicate this):

> package main
import (
	anything "example.com/m"
	"fmt"
)
func main() {
	anything.Println("hello")
	fmt.Println("world")
}

As 'a' comes before 'f', gofmt considers this correct import order. When I hit save in VSCode with gofumpts - this order is changed to (with a space between fmt and anything)
> import (
	"fmt"
	anything "example.com/m"
)

**Comment by mvdan** [comment]
Yes, this is by design. See the README:

> std imports must be in a separate group at the top

**Comment by rekkerz** [comment]
I don't see the support to turn off a specific added rule, guess that would be a nice addition.
For time being, how would I go about turning off the extra rules in VSCode?

**Comment by mvdan** [comment]
No, there is no configurability, just like gofmt. You can turn off gofumpt in VS Code, if you want.

**Comment by rekkerz** [comment]
No, I love this package! I'll see if I can find time to work on configuration options! :)
