### ISSUE TITLE
format: provide the "simplify" feature

### ISSUE THREAD

**Issue by karelbilek** [mvdan/gofumpt#115]
Hi,

would you consider adding support for using gofumpt as a library? It would be useful to me right now :)

What would be "enough" is exporting `func processFile(filename string, in io.Reader, out io.Writer, stdin bool) error` outside.

But all those global options/the error output on `fmt` etc would make the usage a bit weird. So I guess it's a bigger task than just renaming `processFile` to `ProcessFile`. :D

**Comment by mvdan** [comment]
Do you mean https://pkg.go.dev/mvdan.cc/gofumpt/format?

**Comment by karelbilek** [comment]
Ah, I see :)

That still doesn't seem to do the simplifying, and there seem to be some difference with the import sorting. But good start :)

I'll see if that is actually not enough for my purpose.

**Comment by karelbilek** [comment]
yep it's good. Feel free to close, or leave it open if you want to add simplification to exports too

**Comment by mvdan** [comment]
I don't follow. Maybe provide an example of what you mean.

**Comment by karelbilek** [comment]
This function doesn't seem to do the simplification, that is enabled by `gofumpt -s` (as that's done at different package).

I will paste example tomorrow.

**Comment by mvdan** [comment]
Right. The format API is for gofumpt's own features, not gofmt's. gofmt's simplification feature is not available as a Go API anywhere.

**Comment by mvdan** [comment]
Thinking about it again, given that gofumpt enforces gofmt's simplify flag, it's weird that it's not applied via the Go API. Pure Go users like gopls are getting a different experience, so this should be fixed.

**Comment by karelbilek** [comment]
thanks :)
