### ISSUE TITLE
Internal imports mixed with std imports

### ISSUE THREAD

**Issue by lewislbr** [mvdan/gofumpt#117]
Hello, thanks for this package, this is what the `go fmt` should be! 😬 

I've recently installed and ran into this issue:

The internal imports are treated as if they were standard library imports and are grouped together alphabetically.

gofumpt version: `v0.1.1`
Go version: `go1.16.2 darwin/amd64`

Expected result:

```go
import (
	"stdpackage"

	"internal/foo"
	
	"third-party-package/baz"
)
```

Actual result:

```go
import (
        "internal/foo"
	"stdpackage"
	
	"third-party-package/baz"
)
```

Video:

https://user-images.githubusercontent.com/35342598/112524625-5711cc00-8da0-11eb-8641-8a9cd8d35c17.mov

Test repo:

[gofumpt-test.zip](https://github.com/mvdan/gofumpt/files/6207061/gofumpt-test.zip)

Additionally, third-party imports are not grouped if they have at least a blank line between them:

https://user-images.githubusercontent.com/35342598/112526313-174be400-8da2-11eb-80d0-467ca6756e23.mov

Let me know if it can be replicated and if I can help.

**Comment by mvdan** [comment]
This is behaving as intended; any import paths that don't start with a domain name are reserved by the Go toolchain, and as such are considered standard library. See https://github.com/golang/go/issues/32819.

The long-term fix here is to use a proper module path prefix, like `foo.bar/internal/foo`. It doesn't have to be a real domain, you could use `foo.local`. Or, for quick things, see https://github.com/golang/go/issues/37641 which explicitly assigns `example/` and `test/` to third-party modules.

If your objective is to avoid a module path prefix at all costs, then I think your only option is https://github.com/golang/go/issues/44649, though that's a GOPATH transition helper and I'm not sure if it would stick around forever.

**Comment by lewislbr** [comment]
Ahhh I see. Thanks for the insight.

I see the `goimports` tool respects the separation from std imports if there is a blank line in between, and even it divides the internal imports from the third-party ones, so 

```go
import (
	"stdpackage"
	
	"third-party-package/baz"
        "internal/foo"
)
```

becomes

```go
import (
	"stdpackage"

        "internal/foo"
	
	"third-party-package/baz"
)
```

Would it make sense to replicate that behavior?

**Comment by mvdan** [comment]
The only reason goimports obeys that is because it doesn't join std imports at all. So it's only better for you in this scenario because it lacks the feature entirely :)

**Comment by lewislbr** [comment]
Interesting 😬 

I guess this can be closed then. Thanks!

**Comment by mvdan** [comment]
FYI, see https://github.com/mvdan/gofumpt/issues/187#issuecomment-1028108114; I'm currently thinking we could do better for everyone by looking at the main module's path.
