### ISSUE TITLE
Docs: Clarify order for Goland

### ISSUE THREAD

**Issue by eriksw** [mvdan/gofumpt#118]
Should the file watcher rule to run gofumpt go before or after a file watcher for goimports?

**Comment by mvdan** [comment]
I think GoLand has its own feature to add/remove/organize imports, so you shouldn't be setting up goimports at all. Perhaps @dlsniper can correct me if I'm wrong.

**Comment by eriksw** [comment]
It's simpler to use the file watcher (on-save) than to try and get the formatting options to produce the same output. The import optimization also isn't always applied, i.e. GoLand itself won't touch mis-organized imports if you open up a file that was edited by something else and make a change that doesn't modify the imports.

**Comment by mvdan** [comment]
Then I'm not sure. I guess gofumpt should go after, because formatting is generally less invasive than adding/removing imports.

**Comment by mvdan** [comment]
I assume that answers your question.
