### ISSUE TITLE
Optional flag to disable all import sorting?

### ISSUE THREAD

**Issue by sk0g** [mvdan/gofumpt#120]
I'm sure the default settings work for many, but when looking at this tool, it doesn't let you set a `local` prefix, like `goimports` does. As such, I am looking for a way to use `goimports` in conjunction with `gofumpt`.

I set them both up as file watchers in GoLand, but the issue there is that `goimports` is much faster, and always finishes first. Which makes the file's imports nice for a second. Then `gofumpt` finishes, and undoes all the imports sorting done by `goimports`, with it's mangled version.

So for example, `goimports -local abc -w $FilePath` formats like this:
```go
import (
    "net/http"

    "abc"
    "abc/xyz"

    "github.com/external/package"
)
```

`gofumpt` formats it like this:
```go
import (
    "abc"
    "abc/xyz"
    "net/http"

    "github.com/external/package"
)
```

So is there a way to skip the imports sorting entirely, and leave that to `goimports`? If not, and if it's doable, I would appreciate pointers as to how to get that done!

Ideally this just passes on the `local` arg to `goimports`, which might solve the issue of overwriting as well. Even if this didn't touch the imports block at all, I'm not entirely sure if the conflicting finish times would be an issue or not still.

PS I love the tool, and have been manually enforcing a few of the rules already, and agree with most of the other rules. Just a shame it's incompatible with how the project currently formats imports, or we would be using it already :)

**Comment by karelbilek** [comment]
gofumpt also have `gofumports` command, which is goimports with gofumpt+goimports. Maybe that has `-local`? (just a wild guess)

**Comment by karelbilek** [comment]
Ah, gofumports no longer exists.

https://github.com/mvdan/gofumpt/commit/38fc491470bae6f44e2d38b06277dd95cf1bdf97

**Comment by sk0g** [comment]
@karelbilek That would certainly have been worth a look, but [it's been removed.](https://github.com/mvdan/gofumpt/commit/db5cf5b93811e2f68fe03cfc37a931ae0c82413b#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR15-R29)

Worst case scenario I could fork it and remove the import sorting functionality entirely, I guess.

**Comment by karelbilek** [comment]
```
Anyone who still uses gofumports should consider switching. The
alternatives are running goimports and gofumpt separately, using the
mvdan.cc/gofumpt/format Go API, or sticking to v0.1.0 for a little
while.
```

I see. :(

**Comment by karelbilek** [comment]
well one way to your original problem is... to just create a manual script that does both, in the order gofumpt-goimports, and put it to path...

**Comment by sk0g** [comment]
That's what I was trying too actually. In GoLand, chaining them together using either ` && `, or `; ` didn't work. Not entirely sure what shell they use for the file watchers, but that may be worth a look into as well.

**Comment by mvdan** [comment]
What you're running into here is unrelated to `-local`; it's the rule that joins standard library imports. See https://github.com/mvdan/gofumpt/issues/117#issuecomment-813349378. You shouldn't be using module paths like `abc`, because they are reserved.

I plan on enhancing the feature with https://github.com/mvdan/gofumpt/issues/38, but that wouldn't change the logic to join all standard library imports, nor would it mean adding a `-local`. This tool replaces `gofmt` after all, not `goimports`.

Hope that clarifies things. I know it's confusing and perhaps frustrating, but I don't think supporting reserved module paths makes sense in the long run :)

**Comment by sk0g** [comment]
@mvdan the module prefixes aren't actually `abc` - I was just providing that as an example. 

I had a look at this project's code, and noticed something different with the [go.mod](https://github.com/mvdan/gofumpt/blob/master/go.mod#L1) file - your module name is `{domain_name}/{repo_name}`, while the project I'm running into this issue with, the module name is just `{repo_name}`. 

I had a quick play around with renaming the module name to start with a domain name, and while it produced a gigantic diff, it seems to play nicely with `gofumpt` now, so it can be the lone file watcher and makes the code all nice and tidy now. 

So this issue is resolved for me now, thanks for the help!

**Comment by mvdan** [comment]
Right, what I meant is that not using a domain name - not having a dot - means that you're using a path reserved by the Go toolchain, for paths like the standard library. So gofumpt assumes it's std.

Glad that worked for you :) Closing.

**Comment by mvdan** [comment]
FYI, see https://github.com/mvdan/gofumpt/issues/187#issuecomment-1028108114; I'm currently thinking we could do better for everyone by looking at the main module's path.
