### ISSUE TITLE
Current line seperators are not respected

### ISSUE THREAD

**Issue by sk0g** [mvdan/gofumpt#121]
Instead of detecting and keeping the formatted file's line seperators, `gofumpt` always uses the UNIX `\n` character. Running it on a large project with `\r\n` endings, causes a diff line on every single file in the project. 

From what I can tell, it's related to this line:
https://github.com/mvdan/gofumpt/blob/0952458e3d6b38a311cd744b440dbcd63ffb0c42/gofmt.go#L293

**Comment by mvdan** [comment]
That just formats diffs, it's not what you're after.

The piece of code that actually prints Go into bytes is https://golang.org/pkg/go/printer/. I'm not in control of that, and I'm pretty sure that gofmt will enforce unix-style line endings too.

**Comment by sk0g** [comment]
@mvdan  Yeah you're right, that's odd. I've always run `goimports`, but something else about the IDE must have changed then. `git reset --hard`, which triggers file watchers, with `gofumpt` disabled and `goimports` enabled produces the same behaviour too.

**Comment by mvdan** [comment]
I'm going to close this then. Obeying CRLF line endings is not within scope of this tool, because it's not supported by gofmt either.
