### ISSUE TITLE
404 vscode docs link in README

### ISSUE THREAD

**Issue by Qinusty** [mvdan/gofumpt#122]
`official docs` link to https://github.com/golang/tools/blob/master/gopls/doc/vscode.md is 404 in README.md section [visual-studio-code ](https://github.com/mvdan/gofumpt/blob/master/README.md#visual-studio-code)

**Comment by mvdan** [comment]
You're right, it was deleted as of January: https://go-review.googlesource.com/c/tools/+/283644

@stamblerre where should we point users towards?

**Comment by stamblerre** [comment]
Probably just https://github.com/golang/vscode-go#readme--we've decided to point users to each editor plugin instead of the gopls docs.

**Comment by mvdan** [comment]
Fair enough, thanks!

@Qinusty do you want to send a PR?
