### ISSUE TITLE
preserve placement of comment directives relative to variable declarations

### ISSUE THREAD

**Issue by buyology** [mvdan/gofumpt#126]
This package:

```go
package p

import "embed"

//go:embed *
var fs embed.FS
var s string
```

gets `gofumpt`ed to

```go
package p

import "embed"

//go:embed *
var (
	fs embed.FS
	s  string
)
```

which no longer compiles (`./embed.go:5:3: misplaced go:embed directive`) since the comment directive is moved above the variable group.

**Comment by mvdan** [comment]
Thanks, definitely sounds like a bug.
