### ISSUE TITLE
gofumpt breaks code

### ISSUE THREAD

**Issue by mpldr** [mvdan/gofumpt#127]
Take the following constraints:
```go
var (
	_ io.ReadCloser = &Decoder{}

	_ io.WriteCloser = &Encoder{}
)
```

If you now comment out the first constraint (no matter if line or  block comment) the resulting reformat breaks the syntax:

```go
var (
	//_ io.ReadCloser = &Decoder{}

	_ io.WriteCloser = &Encoder{}
)
```
becomes:
```go
var (//_ io.ReadCloser = &Decoder{}

var _ io.WriteCloser = &Encoder{}
```

**Comment by mvdan** [comment]
Thanks, this sounds like a bug - and in fact a duplicate of https://github.com/mvdan/gofumpt/issues/119 :)

**Comment by mpldr** [comment]
It is. didn't see that one.
