### ISSUE TITLE
Normalize var and := with zero values

### ISSUE THREAD

**Issue by leighmcculloch** [mvdan/gofumpt#128]
Gofumpt converts some `var` usages to the shorter `:=`, which is wonderful.

Gofumpt could also rewrite var definitions that assume a zero value.

```go
func f() {
	var m map[int]int
	// ...
}
```

Gofumpt could rewrite those definitions using the short form, and provide an explicit zero value.

```go
func f() {
	m = map[int]int(nil)
	// ...
}
```

This change would have three benefits:

1. Using the short form would normalize code so that all definitions are in short form. It would mean there is only one way to define variables inside functions.

2. Providing an explicit zero value would increase readability. The clarity of many types zero values is already pretty good, such as bools, ints and strings. But for other types the zero value is less obvious, and even experienced Go engineers make mistakes with them, such as channels, maps, and slices. This change would cause all zero definitions to be clear for the reader.

3. The increased clarity in 2 may help developers quickly identify bugs.

**Comment by mvdan** [comment]
I'm not convinced that this would be more consistent though, because Go doesn't have a truly uniform way to say "zero value" for any type. The only way is `var v T`.

For example:

```
var v interface{}
var v []int
var v float64
var v map[string]int
var v struct{}
var v uint
var v bool
```

These are very uniform, and you can even group them via `var ( ... )`. Now, we'd conver them to:

```
v := interface{}(nil)
v := []int(nil)
v := float64(0)
v := map[string]int(nil)
v := struct{}{}
v := uint(0)
v := false
```

You'd also get inconsistencies like - do you write `bool(false)` and `int(0)`? If you do, that's slightly more consistent, but the type conversions are redundant.

All in all, I just don't think it makes sense to enforce this conversion. `var name T` makes sense for as long as Go doesn't have another way to say "zero value of T" in a completely uniform way.

**Comment by leighmcculloch** [comment]
> I'm not convinced that this would be more consistent though, because Go doesn't have a truly uniform way to say "zero value" for any type. The only way is `var v T`.

That's a good point, I hadn't considered consistency from that angle. I was thinking of it being more consistent from the perspective that all declarations would look the same:

```go
i := 0 // instead of var i int
i := 1
```

```go
m := map[int]int(nil) // instead of var m map[int]int
m := map[int]int{}
```

> do you write `bool(false)` and `int(0)`?

I would choose to  have zero declarations use their shortest form, so remove unnecessary casts for untyped default types.

> `var name T` makes sense for as long as Go doesn't have another way to say "zero value of T" in a completely uniform way.

Makes sense.

Am I correct in understanding that the distinction you're making is that the consistency in how to write a zero value (`var v T`) is more important than the clarity of what the zero value is (`nil`,  `0`,  `false`, `{}`, etc).

**Comment by mvdan** [comment]
> Am I correct in understanding that the distinction you're making is that the consistency in how to write a zero value (`var v T`) is more important than the clarity of what the zero value is (`nil`, `0`, `false`, `{}`, etc).

Yes. I don't think either method is always best, and that's what means we can't enforce a choice on the user.

Other forms, like `var name = value`, really do benefit from the consistency without drawbacks - but if a type is involved, we can't take the consistent zero value away from the user.

Ultimately you can still choose to use either form in this case, and gofumpt shouldn't intervene. Maybe we can revisit this if Go ever does get a universal zero value.
