### ISSUE TITLE
add a way to inspect gofumpt's own version by formatting a Go file

### ISSUE THREAD

**Issue by mvdan** [mvdan/gofumpt#130]
gofumpt often ends up being used indirectly, such as via higher level tools like gopls or "multi linters".

That can be confusing for end users and myself alike, because when they find bugs and report them, it's pretty tricky to know for sure what version of gofumpt their editor is using.

That's easy if they just use `gofumpt -w file.go`, as they can just do `gofumpt -version`, but if they indirectly use gofumpt as a library, they don't have access to that same version flag - the `gofumpt` tool they have in their $PATH might not be the same version, or might not be installed at all.

Here's an idea, thanks to some folks over on the Gophers Slack. Have a magic comment that's recognized by gofumpt and replaced to contain its own version too. Then, when a user finds a bug while formatting a file in their editor, they can insert this comment and format again to have enough details to raise a good bug report.

This comment would include gofumpt's own version, as expected - just like `gofumpt -version`. It will also include any options or flags which affect gofumpt's behavior, such as `-lang` or `-extra`, to make sure we can reproduce the same behavior the user is seeing.

Originally I was thinking `//gofumpt:version`, but since we'll include other information such as options, I think `//gofumpt:diagnose` is best.

So, if gofumpt sees any comment starting with `//gofumpt:diagnose`, it will be replaced by a comment such as:

```
//gofumpt:diagnose v0.1.1-0.20210524140936-ba6406b58f36 -lang=1.16
```

Older versions of gofumpt would not touch this comment directive at all, so if a user can't make the comment work, at least we know they're on an old version.

**Comment by colinnewell** [comment]
Would it also make sense to provide the location the binary is running from?  I can imagine a user realising their problem is that they simply need to upgrade, but aren't aware of where it's running from.
