### ISSUE TITLE
document "reserved standard library" module paths

### ISSUE THREAD

**Issue by twmb** [mvdan/gofumpt#135]
If I have the following directory structure:

```
go.mod
main.go
pkg/thing/thing.go
```

with the following file contents:

go.mod:
```go
module foo

go 1.16
```

main.go:
```go
package main

import (
	"fmt"

	"foo/pkg/thing"
)

func main() {
	fmt.Println("hello")
	thing.Print()
}
```

pkg/thing/thing.go:
```go
package thing

func Print() {
	println("foo")
}
```

Then gofumpt will change main.go's import block such that the foo/pkg/thing import is tied to the stdlib fmt import.

I think this is only possible to detect with the current gofumpt implementation if gofumpt reads the go.mod file to know what module it is in. If `import == module || strings.HasPrefix(import, module + "/")`, then the import is non-standard. I do not see a way to have this same logic if just relying on the ast. Another potential option is to just have a list of stdlib imports, but this obviously is not future proof for when the stdlib adds new modules (a user would have to update gofumpt, which also would then have the obligation of staying up to date with Go releases).

**Comment by mvdan** [comment]
You seem to understand what's going on here :) Have you seen https://github.com/mvdan/gofumpt/issues/117#issuecomment-813349378? I might add that to a FAQ since this keeps coming up.

**Comment by mvdan** [comment]
> I think this is only possible to detect with the current gofumpt implementation if gofumpt reads the go.mod file to know what module it is in.

That's planned for https://github.com/mvdan/gofumpt/issues/38, so that would affect grouping imports too. Still, though, you shouldn't be using paths which are "reserved for std" as per the explanation above.

**Comment by twmb** [comment]
Yep -- I updated the module in question to be a github based name, not a single word. given #38 and your golang issue, I'm thinking the only thing to do here would be to update the FAQ.

**Comment by mvdan** [comment]
Thank you - agreed.

**Comment by mvdan** [comment]
I'll leave this open as a doc reminder for myself, if that's OK :)

**Comment by mvdan** [comment]
FYI, see https://github.com/mvdan/gofumpt/issues/187#issuecomment-1028108114; I'm currently thinking we could do better for everyone by looking at the main module's path.
