### ISSUE TITLE
running gofumpt outside of module misses some formatting

### ISSUE THREAD

**Issue by twmb** [mvdan/gofumpt#137]
Dirs:
```
inner/go.mod
inner/foo.go
```
Contents,
go.mod:
```
module foo.local

go 1.16
```
foo.go:
```go
package main

import "io/ioutil"

func main() {
	ioutil.WriteFile(".", nil, 0600)
}
```

`gofumpt -w inner/foo.go` does not catch the octal problem:

```
[09:54:27]
twmb@h4x3r:~/TEST
$ gofumpt -w inner/foo.go 

[09:54:30]
twmb@h4x3r:~/TEST
$ git diff

[09:54:32]
twmb@h4x3r:~/TEST
$ cd inner/

[09:54:34]
twmb@h4x3r:~/TEST/inner
$ gofumpt -w foo.go 

[09:54:37]
twmb@h4x3r:~/TEST/inner
$ git diff
diff --git a/inner/foo.go b/inner/foo.go
index fbcc867..f399e27 100644
--- a/inner/foo.go
+++ b/inner/foo.go
@@ -3,5 +3,5 @@ package main
 import "io/ioutil"
 
 func main() {
-       ioutil.WriteFile(".", nil, 0600)
+       ioutil.WriteFile(".", nil, 0o600)
 }
```

**Comment by twmb** [comment]
Also, this reformatting does not seem to happen on save in vim with vim-go with the following setup:
```
let g:go_fmt_command="gopls"
let g:go_gopls_gofumpt=1
```

**Comment by mvdan** [comment]
Yep, this is by design. Using the `0o` syntax is good for consistent and readable formatting, but it requries newer versions of the Go language. If the tool runs outside of a module, it can't assume that the language version being used is, so it defaults to 1.0. You can override this with `gofumpt -lang=` too.

**Comment by twmb** [comment]
Very cool, that makes sense. Unrelated, but do you happen to know if it's possible to have the `-extra` flag enabled in a .vimrc? No worries if no. I think this issue can be closed either way :)

**Comment by mvdan** [comment]
It's certainly possible in theory to use gopls flags to pass options through to gofumpt, but in practice those aren't wired up yet. See https://github.com/golang/go/issues/43998. You should comment on that issue.

**Comment by twmb** [comment]
Thanks! I'll close this then!
