### ISSUE TITLE
Imports using GCI ? Getting a linting error because of grouping.

### ISSUE THREAD

**Issue by iangregsondev** [mvdan/gofumpt#138]
Hi,

I have been using gofumpt and I am pretty sure I had it working perfectly before but I recently reinstalled my goland IDE..

It is still formatting but my imports are not being grouped.

I installed gofumpt using "go install"

```
❯ gofumpt --version
v0.1.1


❯ which gofumpt 
/Users/ian/.gvm/pkgsets/go1.16.4/global/bin/gofumpt

```

![image](https://user-images.githubusercontent.com/2370364/128496456-96a154a4-168e-4404-b3ac-fe0ca61932fd.png)

Does anybody know what I am doing wrong?

Thanks in advance

**Comment by mvdan** [comment]
I think you're mixing two formatters: https://github.com/daixiang0/gci

gofumpt is compatible with gofmt, but it's not designed to be used at the same time as other tools that want to be in control of formatting, like gci. So you should probably disable gci.

If you want gofumpt to do more with import groups, see https://github.com/mvdan/gofumpt/issues/38 - you can leave your opinion there :)

**Comment by iangregsondev** [comment]
Thanks, @mvdan, I will take a look at #38 and in the meantime, I will diable the gci.
