### ISSUE TITLE
Not Decimal to octal：0644->0o644

### ISSUE THREAD

**Issue by andyli029** [mvdan/gofumpt#144]

**Comment by mvdan** [comment]
I don't understand. Please explain clearly.

**Comment by twmb** [comment]
This might be the same as https://github.com/mvdan/gofumpt/issues/137?

**Comment by andyli029** [comment]
> This might be the same as #137?
Yes.

**Comment by andyli029** [comment]
> I don't understand. Please explain clearly.
 #137
