### ISSUE TITLE
wishlist: transform single line struct initialisations to multiline

### ISSUE THREAD

**Issue by dnwe** [mvdan/gofumpt#15]
_Caveat: This may just be personal preference, so feel free to close if you think it is too controversial a change, but it does comply with the "preserve gofmt compatibility" so maybe it is OK..._

--

I'd like `gofumpt` to either reformat all single-line struct initialisations into multi-line per field initialisation – or if that is too big a change, I'd like it to reformat them if some threshold of number of fields being initialised is exceeded. Even better if it were to include the functionality of [keyify](https://github.com/dominikh/go-tools/tree/master/cmd/keyify) to convert any unkeyed fields to keyed ones. 

i.e.,

```diff
diff --git a/a/main.go b/b/main.go
index 3ddfc0e..46cccae 100644
--- a/a/main.go
+++ b/b/main.go
@@ -10,19 +10,33 @@ type person struct {
 
 func main() {
 	// This syntax creates a new struct.
-	fmt.Println(person{"Bob", 20})
+	fmt.Println(person{
+		name: "Bob",
+		age:  20,
+	})
 
 	// You can name the fields when initializing a struct.
-	fmt.Println(person{name: "Alice", age: 30})
+	fmt.Println(person{
+		name: "Alice",
+		age:  30,
+	})
 
 	// Omitted fields will be zero-valued.
-	fmt.Println(person{name: "Fred"})
+	fmt.Println(person{
+		name: "Fred",
+	})
 
 	// An `&` prefix yields a pointer to the struct.
-	fmt.Println(&person{name: "Ann", age: 40})
+	fmt.Println(&person{
+		name: "Ann",
+		age:  40,
+	})
 
 	// Access struct fields with a dot.
-	s := person{name: "Sean", age: 50}
+	s := person{
+		name: "Sean",
+		age:  50,
+	}
 	fmt.Println(s.name)
 
 	// You can also use dots with struct pointers - the
```

**Comment by mvdan** [comment]
Thanks for the issue. Firstly, I think one or two fields in a single line, even if other fields are ommited, is fine. And I think a considerable amount of Go developers would agree here, or at least be impartial, so I think that change would be too controversial.

However, if those one or two fields made the line very long (see #2), I'd agree that it should be split up. But that's already covered in that issue.

Having said this, perhaps we can work with a larger threshold. For example, I probably wouldn't put four or five fields on a single line, even if the line wasn't long in total. Perhaps 3 or 4 is the magic number that would be a good compromise. I'd have to give it a try and see if much idiomatic Go code out in the wild agrees or not.

Also, you talk about "omitted fields" in your examples, but remembr that gofumpt works with just the syntax, so it cannot know if any fields are being ommitted. That's type information it just doesn't have.

Lastly, as for keyify, in general it's only enforced to use explicit field names when using struct types from external packages. Again, that's the kind of thing that one needs type information from. Without type information, gofumpt can't tell what the implicit field names actually are. And adding type information is just not an option.

**Comment by dnwe** [comment]
👍

**Comment by mvdan** [comment]
I'd like to leave this open to make a decision when I'm fully sober :)

**Comment by dnwe** [comment]
Sure 😂

**Comment by adiabatic** [comment]
> Caveat: This may just be personal preference

For what it's worth, I have the opposite personal preference. If I write something like this all on one line, I want the vertical compactness preserved.

**Comment by mvdan** [comment]
@adiabatic to pick everyone's brains a little... where's your threshold? Line length? Number of fields/expressions? Code "complexity"?

Me personally, I wouldn't force any of the examples in the original post to be multi-line. But if one line had more than four fields and took over eighty columns, I probably would, for example.

**Comment by elagergren-spideroak** [comment]
A combination of both. Max 80 chars or ~3 fields, whatever comes first. But I also break it up if I have a long-ish string.

**Comment by adiabatic** [comment]
> where's your threshold?

Eh, it depends. That's the main reason I wouldn't want a program changing it for me. It's usually a combination of…

- line length (I don't want it to be abnormally long, but I tend to be tolerant of over-80 column overages since I have all sorts of differing window widths and font sizes)
- whether I have another struct being initialized right above or below that also fits on one line (I like vertical symmetry)

The three-fields limit would annoy me if I ever initialized something like this and it got reformatted:

```go
backgroundColor := RGBA{R: 0.0, G: 0.0, B: 0.0, A: 1.0} // black
color :=  RGBA{R: 0.5, G: 1.0, B: 1.0, A: 1.0} // greenish-blue
```

Incidentally, I like it when gofmt leaves lines like `func (t *T) String() { return t.name }` alone, in their one-line glory. As you might guess, I die a little inside when `if err != nil { return err }` gets broken up into a three-line monstrosity, consuming vertical space well out of proportion to its importance in the code.

**Comment by mvdan** [comment]
Thanks all for the feedback. I'm pretty convinced that this is too subjective and risky. We can deal with long lines as part of #2.
