### ISSUE TITLE
how to use with Jetbrains Goland?

### ISSUE THREAD

**Issue by 68696c6c** [mvdan/gofumpt#16]
Is there any way to use this with Jetbrains Goland or as a stand-alone CLI tool?

**Comment by mvdan** [comment]
As a stand-alone CLI tool, sure. `gofumpt` is just a drop-in replacement for `gofmt`.

I don't know about Goland.

**Comment by 68696c6c** [comment]
Ok, standalone tool works for me.  But could you consider adding content to the installation section of the README making it clear how to use this as a standalone tool?  Currently the README seems to imply this is only a VS Code plugin...

**Comment by mvdan** [comment]
Yes, the person that edited the README made it kinda confusing. Will clarify it.
