### ISSUE TITLE
don't group exported and unexported methods of an interface together

### ISSUE THREAD

**Issue by ainar-g** [mvdan/gofumpt#168]
Version: `v0.2.0`.

Before:

```go
type I interface {
	A()
	B()

	c()
}
```

After:

```go
type I interface {
	A()
	B()
	c()
}
```

Perhaps `c` shouldn't be grouped together with `A` and `B`, since it is unexported?

In the real code that inspired this issue, the `c` is a “marker method” for members of the “sum type” `I`, while `A` and `B` are methods that return data common to the members of the “sum type”.

<sup>(I have filed this in the `unused` repo at first.  Apologies for the noise once again.)</sup>

**Comment by mvdan** [comment]
Sounds good. Would you like to send a fix with a test case?

**Comment by ainar-g** [comment]
Unfortunately, I won't be able to do that, sorry.  At least not within the next month or so.  I will probably be able to  do that later, but if anyone wants to send the fix in the meantime, please feel free.

**Comment by mvdan** [comment]
No worries. I'll leave it up for grabs for a few days.

**Comment by ejain** [comment]
Not grouping exported with unexported methods seems reasonable, but looks like now you are forced to group all your exported and all your unexported methods! e.g. the following is no longer allowed:

```go
type i1 interface {
	doA()
	doB()
	
	undoA()
	undoB()
}
```

**Comment by mvdan** [comment]
I see you raised https://github.com/mvdan/gofumpt/issues/186, so I'll reply there.
