### ISSUE TITLE
Linefeed removed after multi line comments in composite literals

### ISSUE THREAD

**Issue by cckim** [mvdan/gofumpt#170]
Composite literals have blank lines removed, but it seems to treat the trailing `*/` of a multi-line comment as a blank line.

If we add the following testcase to composite-literals-leading-lines
```
var _ = map[string]string{
        /*
        */

        "foo": "bar",
}
```
formatting produces:
```
var _ = map[string]string{
        /*
        */ "foo": "bar",
}
```
This seems like an unintended consequence of https://github.com/mvdan/gofumpt/commit/f2d9f32be31becb2f4d626dc07f83ca26268eb7f

Also, this creates a conflict with gofmt v0.1.7 which wants (removed blank space):
```
var _ = map[string]string{
        /*
        */"foo": "bar",
}
```

**Comment by mvdan** [comment]
Thanks - this seems to be one of the cases where we forgot to check if there are any comments in those "empty" lines we're removing. If there are comments, we don't want to remove their newlines.

Leaving as "good first issue" for a couple of days to see if someone wants to pick it up :)
