### ISSUE TITLE
Single-value struct clarification

### ISSUE THREAD

**Issue by myshkin5** [mvdan/gofumpt#182]
Hello!

I'm noticing that some single-value, single-line structs are left alone while others are reformatted so that the single value is on its own line. This one was left alone (regardless of if I put the value on its own line):

```go
type usualAdaptor struct{ m *moqUsual }
```

This line will get reformatted:

```go
type exportedUsualRecorder struct{ r *exported.MoqUsual_Usual_fnRecorder }
```

This is what the reformatted code looks like:

```go
type exportedUsualRecorder struct {
	r *exported.MoqUsual_Usual_fnRecorder
}
```

Just looking for clarification and any sort of rule to point to. Is it the line length? Maybe the odd underscores in the name?

Thanks in advance!

**Comment by mvdan** [comment]
This is something done by gofmt, so it's not one of gofumpt's added rules:

```
$ cat f.go
package p

type usualAdaptor struct{ m *moqUsual }

type exportedUsualRecorder struct { r *exported.MoqUsual_Usual_fnRecorder }
$ gofmt f.go
package p

type usualAdaptor struct{ m *moqUsual }

type exportedUsualRecorder struct {
	r *exported.MoqUsual_Usual_fnRecorder
}
```

I do seem to recall that gofmt has some basic heuristics for what is reasonable to fit into a single line. Those heuristics are rather limited and conservative, though.
