### ISSUE TITLE
Allow leading zero integers without octal mark

### ISSUE THREAD

**Issue by Bysmyyr** [mvdan/gofumpt#184]
Hello! 

We have quite bunch of test code where we like to have leading zero integers just to keep readability better. Could there be some solution to prevent those 0o:s to be inserted(without adding nolint to every line).

Thanks!

**Comment by mvdan** [comment]
You do realise that leading zeros means that the numbers are octal, not decimal? :) It's not just a matter of readability.

**Comment by Bysmyyr** [comment]
yeah, here it is used for normal numbers 00 and 05. Just test code. Not optimal but works.

**Comment by Bysmyyr** [comment]
we decided to remove them
