### ISSUE TITLE
Support optimizing field alignment

### ISSUE THREAD

**Issue by Seirdy** [mvdan/gofumpt#185]
[`fieldalignment`](https://go.googlesource.com/tools/+/refs/heads/master/go/analysis/passes/fieldalignment) is the official tool for ordering struct fields to reduce memory.  `fieldalignment -fix ./...` can sort a project's fields automatically.

gofumpt incorporated `gofumports` functionality for sorting imports; it seems appropriate to also incorporate field-sorting from `fieldalignment` or equivalent.

**Comment by mvdan** [comment]
`gofumports` has been deprecated and removed for some time, so it shouldn't be used as a precedent.

Still, sorting or organizing imports is entirely reasonable for a code formatter, but I don't think reordering fields for the sake of memory alignment is. Reordering imports does not change the behavior of the program at all, but reordering fields does.

Finally, there's one reason why we definitely can't do this, even if we wanted to: fieldalignment, like many other go/analysis tools, uses go/types. gofumports doesn't need it at the moment, and I can't see why a code formatter should ever need type information. Beyond being out of scope, it would also slow the tool significantly, probably making it many times slower.
