### ISSUE TITLE
collapse short error declare-check statements into one line

### ISSUE THREAD

**Issue by mvdan** [mvdan/gofumpt#19]
```
err := foo()
if err != nil {
    return err
}
```

Since both lines are short, I'd personally write this like:

```
if err := foo(); err != nil {
    return err
}
```

Advantages:

* Shorter and simpler
* We don't pollute the parent scope with `err`
* Impossible to use the wrong `err` value later by mistake

However, it's not clear what we should do if the code uses `err = foo()`, or if changing the code would break the parent scope as `err` is no longer declared. For example:

```
err := foo() // merging the lines would stop declaring err
if err != nil { ... }
b, err = bar()
if err != nil { ... }
```

I'd love for gofumpt to be able to do this, as I see code like this too often. However, it's going to be hard to do it correctly, as the tool doesn't have any type information.

And even if it did, one could argue that any rule needing type information isn't a formatting rule. Perhaps it fits better into a "code simplification" tool or some other static analysis tool.

Filing this issue to get more opinions.

**Comment by adiabatic** [comment]
I agree that this would be out of scope for a formatter. If I do something like

```go
err := foo()
if err != nil {
    return err
}
```

I expect (and would prefer) err to still be in scope after it all ends. If I want err to stop existing after the error block, I can use the if x; y form.

**Comment by mvdan** [comment]
Yeah, I agree. I think this fits more into a code simplification analyzer; particularly since `go/analysis` and the LSP gained the ability to show the user suggestions instead of warnings.
