### ISSUE TITLE
Move inline comments of struct/interface defition to a new line

### ISSUE THREAD

**Issue by ebati** [mvdan/gofumpt#194]
For now gofumpt allow both
```
type S struct { // Comment
}
```
and 
```
type S struct {
    // Comment
}
```
formats. I suggest second version. If a comment is for documentation, it should be written above the definition. If a comment is related to internals or you don't want it to appear in docs. it should be written inside the struct.

The test case in `composite-multiline.txt` can be a valid case for inline comment, but not sure:
```
type T struct {
	Foo          // comment
	Bar struct { // comment
	}
}
```

I would be happy to hear your feedback.

**Comment by mvdan** [comment]
I'm a bit indifferent on this one; I don't see anything particularly wrong with your first block of code. I think gofumpt should only forbid formatting that never makes sense, and I can imagine some scenarios where a human might prefer the inline comment.
