### ISSUE TITLE
Sorting does not work well for external imports (if custom name given)

### ISSUE THREAD

**Issue by Dentrax** [mvdan/gofumpt#206]
I'm using the following imports:

```golang
"github.com/google/go-containerregistry/pkg/authn"
"github.com/google/go-containerregistry/pkg/name"
"github.com/google/go-containerregistry/pkg/v1/remote"
"github.com/sigstore/cosign/cmd/cosign/cli/options"
"github.com/sigstore/cosign/pkg/oci"
"github.com/sigstore/cosign/pkg/oci/mutate"
ociremote "github.com/sigstore/cosign/pkg/oci/remote"
"github.com/sigstore/cosign/pkg/oci/static"
sigPayload "github.com/sigstore/sigstore/pkg/signature/payload"
```

I think the problem here is that `cosign/pkg/oci/remote` should lower than `cosign/pkg/oci/static` since alphabetically `s` > `r`:

```golang
ociremote "github.com/sigstore/cosign/pkg/oci/remote"
"github.com/sigstore/cosign/pkg/oci/static"
```

These two lines should be replaced. 

```bash
$ gofumpt --version

v0.1.1
```

Any thoughts on this?

**Comment by mvdan** [comment]
I'm confused. Yes, r comes before s, so that sorting is correct.

But also, you're on an ancient version of gofumpt, so I would say try with the latest version first.

**Comment by Dentrax** [comment]
Oh, I thought I'm maintaining this with _brew_. I confused for a moment and thought _s comes before r_, sorry. Closing this one. 🙈
