### ISSUE TITLE
How to add gofumpt to path?

### ISSUE THREAD

**Issue by nik-don** [mvdan/gofumpt#209]
I'm currently using WSL on Win 10.

Trying to figure how to install gofumpt. I believe I need to add it to the path because I get this message.
```
gofumpt: command not found
```
---

my ~/.bashrc
```
# configure go-1.18
export GOROOT=/usr/local/go
export GOPATH=$HOME/projects/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$HOME/projects/go/bin
```
~/.profile
```
# additional setting for golang
if [ -d "/usr/local/go/bin" ] ; then
    PATH=$PATH:/usr/local/go/bin
fi
```

following these instructions : https://gist.github.com/renevo/fad4db582b4f0edb9ecb767dec689474

**Comment by mvdan** [comment]
I'm sorry but that seems like a Go question, not really for this project in particular - installing any Go program should work the same. As long as your GOBIN is in your PATH, that should work fine. You could try `go install -x` to see where the binary ends up being copied to. For more help, see https://golang.org/wiki/Questions.
