### ISSUE TITLE
Moving to one var block missed one variable

### ISSUE THREAD

**Issue by Jacalz** [mvdan/gofumpt#212]
I was running this project on Fyne, see https://github.com/fyne-io/fyne/pull/2855 for more info. The formatting is, as the PR description says, doing a great job and I am very impressed with it.

However, I noticed that there was one part where it seems to have failed to put all variables inside one block. It managed to get three out of four variables as it seems to somehow have missed the first one.

All necessary information should hopefully be found here: https://github.com/fyne-io/fyne/pull/2855#discussion_r830566398

**Comment by mvdan** [comment]
Thanks for filing this! My guess is that gofumpt saw the comment on the first variable and decided not to group it because of that. But in cases like this one, the comment is for the entire block, so it should be fine.

**Comment by cespare** [comment]
I ran gofumpt over a large codebase (thinking of using it at work) and this was the only real issue I noticed.

**Comment by mvdan** [comment]
Should be fixed now, thanks to @Oiyoo - please test master and let us know.

**Comment by cespare** [comment]
Thanks for the fix! Looks good to me.

@mvdan do you have a particular schedule for releasing? Any chance of a 0.3.2 to include this fix soon?

**Comment by mvdan** [comment]
I'll probably release in a week or two. It should be possible to pin a newer commit if you need master before then.

**Comment by mvdan** [comment]
I promise I'm not dead nor have I forgotten about doing a release :) I recognize a release is way overdue, and it's my priority now. Will do that once Go 1.19 is out and I can merge https://github.com/mvdan/gofumpt/pull/239, which will significantly help when debugging issues downstream.

**Comment by mvdan** [comment]
Better late than never: https://github.com/mvdan/gofumpt/releases/tag/v0.4.0
