### ISSUE TITLE
Gofumpt as an analysis.Analyzer implementation

### ISSUE THREAD

**Issue by sluongng** [mvdan/gofumpt#216]
In order to user gofumpt as part of Bazel's rules_go's nogo static analysis framework, we need a package to export a variable named Analyzer. https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst

```
var Analyzer = ...
```

Analyzer here should be an instance of struct https://pkg.go.dev/golang.org/x/tools/go/analysis#hdr-Analyzer

Given that `gofumpt` is mostly operating over ast.File, I figure it must be relatively straight forward to wrap current implementation to consume an analysis.Pass https://pkg.go.dev/golang.org/x/tools/go/analysis#Pass

WDYT?

**Comment by mvdan** [comment]
See https://github.com/mvdan/gofumpt/issues/78, this is on the roadmap. It's not an easy change though, because right now we modify the AST, and the go/analysis API wants to work on byte-based suggested fixes.
