### ISSUE TITLE
simplify `make`

### ISSUE THREAD

**Issue by qianxi0410** [mvdan/gofumpt#220]
for `make(chan Type, 0)` or `make(map[Type]Type, 0)`,
it can be simplified to `make(chan Type)` and `make(map[Type]Type)`,
and for `make([]Type, len, len )`, we can simplify it to `make([]Type, len)`.

But for map, whether it can be so simplified, I'm not very sure.
My lint doesn't alert me:
![图片](https://user-images.githubusercontent.com/55543743/163773735-ae808268-0cee-486f-af68-292d9e3f04f6.png)

If possible please allow me to submit a pr.

**Comment by qianxi0410** [comment]
see: #221

**Comment by mvdan** [comment]
This is already marked by staticcheck - is there a reason you want gofumpt to do it as well?

Note that gofumpt doesn't implement any code simplification of its own, in the sense of removing expressions or sections of code. The only parts where it does that come from upstream's `gofmt -s`.

One reason I want to be careful about features like these is that gofumpt is a _formatting_ tool, so it should only do minor code transformations where they relate to formatting or where they are so trivial that a fully fledged static analysis tool like staticcheck isn't needed. Perhaps you can argue that your change is easy enough to implement, but at the same time, staticcheck already has it :)

**Comment by qianxi0410** [comment]
You're right, I'm not thoughtful enough as a tool user. Maybe I should fork a copy to satisfy my own thoughts.
Anyway, thanks :D

**Comment by dominikh** [comment]
As for simplifying `make` with maps, see https://github.com/dominikh/go-tools/issues/1070
