### ISSUE TITLE
Goland (jetbrains) File Watcher: gofumpt reports an error, size of X changed during reading...

### ISSUE THREAD

**Issue by iangregsondev** [mvdan/gofumpt#226]
Hi,

Can anyone help ?

I am using a File Watcher in goland to run gofumpt but I am getting the error in the output, this line seems to be executing in gofumpt

```
		return nil, fmt.Errorf("error: size of %s changed during reading (from %d to %d bytes)", filename, size, n)
```

I have a feeling it's because I have multiple watchers, does anybody know of a way around this?

Or maybe it's not multiple watchers but maybe Goland is changing something and there is some kind of race condition.

Here are the watchers that I have enabled.

![image](https://user-images.githubusercontent.com/2370364/168049948-815871d2-c579-4496-845a-9fb2d053908e.png)

and specifically the gofumpt one

![image](https://user-images.githubusercontent.com/2370364/168050093-2d9d6099-1319-48fa-a0ea-0977c44c7d25.png)

Does anybody know how I can fix this?

Thanks in advance

**Comment by mvdan** [comment]
This seems like something you need to figure out with GoLand or your IDE setup. The error is there to prevent race conditions: something edited the file at the same time as gofumpt was running. The error has a purpose, and it's to prevent overriding your code if something saved it at the same time, so I don't think there's anything for me to do here :)

**Comment by iangregsondev** [comment]
Sure, I only posted it to see if anybody else had the same issue as Goland is a popular IDE and I figured that others might have the same issue.

Ok, I will close it. Thanks

**Comment by eriksw** [comment]
I have this issue too and it's really annoying. @iangregsondev Did you ever figure out a way to avoid triggering this?

**Comment by mehdihadeli** [comment]
I have same problem, maybe the issue is using multiple formatter in same time in IDE
