### ISSUE TITLE
Cannot install on Ubuntu / latest Go

### ISSUE THREAD

**Issue by Alexey-T** [mvdan/gofumpt#231]
```
user@PC:~$ go version
go version go1.13.8 linux/amd64
```

I run in terminal:

go get mvdan.cc/gofumpt@latest

this shows error:
```
user@PC:~$ go get mvdan.cc/gofumpt@latest
go: finding mvdan.cc/gofumpt v0.3.1
go: downloading mvdan.cc/gofumpt v0.3.1
go: extracting mvdan.cc/gofumpt v0.3.1
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: downloading github.com/google/go-cmp v0.5.7
go: extracting golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: extracting github.com/google/go-cmp v0.5.7
go: extracting golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: finding golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: finding golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: finding github.com/google/go-cmp v0.5.7
build mvdan.cc/gofumpt: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
user@PC:~$ gofumpt
gofumpt: command not found
```

**Comment by mvdan** [comment]
Your Go version is too old. We don't actually document this, so I should probably add it to the README, but we currently require Go 1.17 or later.

I think Debian and Ubuntu backport newer Go versions to older releases. Go 1.13 hasn't been supported upstream for years now, so you shouldn't be using it to develop Go code in any case.

**Comment by mj-nehme** [comment]
Well, I have `go1.20.1` and still unable to install it!! The same issue exactly.

**Comment by mvdan** [comment]
Are you absolutely sure that you are on 1.20.1? You can verify with `go version`.

**Comment by mj-nehme** [comment]
> Are you absolutely sure that you are on 1.20.1? You can verify with `go version`.

Thanks for the follow up.

Got to solve it, I'll describe it here for those coming later.

The problem was that my `GOPATH` was directing to `~/.go` not `~/go`. However, `gofumpt` was installed in `~/go/bin/gofumpt`.

It seems that since `Go 1.8`, the default `GOPATH` was changed to `~/go`.

I just changed `GOPATH`, updated `PATH` and it worked.
