### ISSUE TITLE
failed to install v0.3.1

### ISSUE THREAD

**Issue by bbx-winner** [mvdan/gofumpt#232]
## Problem

I had tried two ways to install `gofumpt`:

```shell
go get mvdan.cc/gofumpt@latest
```

```shell
go install mvdan.cc/gofumpt@latest
```

Everything went right, but I got the following message without `gofumpt` in my `$GOPATH/bin`. 

```text
//go:build comment without // +build comment
```
When I changed to v0.3.0, I could install `gofumpt` successfully.

## Env
- os: macos
- go version: go version go1.16.5 darwin/amd64

**Comment by mvdan** [comment]
We require Go 1.17 or later at the moment; Go 1.16 is no longer maintained nor supported upstream, and hasn't been for a few months now. The README doesn't say this though, so I'll fix that.
