### ISSUE TITLE
gofumpt does not remove duplicated declarations

### ISSUE THREAD

**Issue by SchumacherFM** [mvdan/gofumpt#24]
Hey there, Thank you for you work on this more stricter tool!

`accounts` is a global variable.

Running `gofumpt -w -s .`

Have:

```
var accounts map[string][]string = map[string][]string{
	"000099999": {"WARENVERKAUF", RECORD_TYPE_TURNOVER},
}
```

Want:

```
var accounts = map[string][]string{
	"000099999": {"WARENVERKAUF", RECORD_TYPE_TURNOVER},
}
```

**Comment by mvdan** [comment]
Thanks for filing the issue. Do you mean this to only match `var x SomeType = SomeType{...}`?

I don't think we could do more than that, given that the tool doesn't have any type information.

**Comment by SchumacherFM** [comment]
Yes I mean `var x SomeType = SomeType{...}` to `var x = SomeType{...}`. If that is not possible, then please close this ticket.

**Comment by mvdan** [comment]
I think this is out of scope; it has very little to do with formatting. This should be done by a code simplifier which has full access to type information. We could deal with the trivial cases that don't require full type information, but that very limited logic would probably confuse users more than anything.

You're probably interested in static analysis tools like this one, which warns you about type conversions which are redundant: https://github.com/mdempsky/unconvert
