### ISSUE TITLE
gofumpt doesn't work with neovim

### ISSUE THREAD

**Issue by aatmasaat** [mvdan/gofumpt#245]
I'm having trouble integrating gofumpt with neovim lspconfig, I'm using neovim v0.7.2 and as per the instructions I've following lines in my config
```lua

require('lspconfig').gopls.setup({
    settings = {
        gopls = {
            gofumpt = true
        }
    }
})
```

I've go v1.18.2, gopls v0.9.5, and gofumpt v0.3.1 on my system, while working with files gopls shows issues as expected but when I save the file gofumpt does not format the code. Is there additional configuration for gofumpt to format on write?

**Comment by mvdan** [comment]
I would ask this question in the gopls project, because this is about their setup with neovim. They are the ones who integrate with gofumpt too. I would be very surprised if there was a bug or problem on our side here :)

**Comment by henvo** [comment]
@halshar Running into the same problem. Have you found a solution?
Thanks for any tips.

**Comment by halshar** [comment]
I'm using [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) and gofumpt was one of the [builtin](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#usage-183) source for null-ls, the plugin was archived but it's still working fine. I am yet to migrate to other source from null-ls
