### ISSUE TITLE
whitespace around multiplication operator

### ISSUE THREAD

**Issue by cwpwd** [mvdan/gofumpt#247]
```
package main

import "fmt"

func main() {
	a, b, c := 3, 4, 5

	if (a*a)+(b*b) == (c*c) {
		fmt.Println("it is!")
	}
}
```

If you `go fmt` on this code (which I found on golang/go issue tracker) you will notice `(c*c)` becomes `(c * c)`

What do you think?

**Comment by mvdan** [comment]
The whitespace in arithmetic operators is chosen by gofmt, not gofumpt. We can't change it without becoming incompatible, so there's nothing to be done here, for better or worse.
