### ISSUE TITLE
gofumpt lint conflict with go-swagger comments

### ISSUE THREAD

**Issue by pmalhaire** [mvdan/gofumpt#249]
This issue is not directly related to gofumpt but it's making it's usage a bit more difficult

When using go-swagger https://github.com/go-swagger/go-swagger to generate swagger doc 

ex :

the file 

```
package handler

// swagger:operation POST /post/{input} myPost
//
// dummy test
//
// ---
//
// parameters:
//   - name: input
//     in: query
//     required: false
//     type: string
//     enum:
//     - enumValue
// responses:
//   "200":
//     description: Success
func handler(){
}
```

is linted by gofumpt to invalid swagger comment
```
package handler

// swagger:operation POST /post/{input} myPost
//
// dummy test
//
// ---
//
// parameters:
//   - name: input
//     in: query
//     required: false
//     type: string
//     enum:
//   - enumValue
//
// responses:
//
//	"200":
//	  description: Success
func handler() {
}
```

to check install go-swagger see https://goswagger.io/install.html

and run the command on both version

```
swagger generate spec -m handler.go
```

gofumpted version returns an error

**Comment by mvdan** [comment]
I'm fairly sure this is a change made by gofmt, not gofumpt. gofumpt does not have any extra rules relating to godocs.

**Comment by pmalhaire** [comment]
and you are right it's a gofmt issue
