### ISSUE TITLE
gofumpt re-formats tabs to spaces (was: New release built with go 1.19?)

### ISSUE THREAD

**Issue by morremeyer** [mvdan/gofumpt#254]
I propose to make a new release built with go 1.19.

go 1.19 improved support for documentation comments a lot, see https://tip.golang.org/doc/go1.19#go-doc.
Other tools, like swagger, have started to adopt this.

The behaviour of gofumpt depends on the go version it is built with (due to the use of `go/printer` from go - see https://github.com/mvdan/gofumpt/issues/244#issuecomment-1234222560 if you want to learn more.

gofumpt is starting to become incompatible with documentation comments using those new features as it formats them in a way that breaks the use of those new features.

I'll make a PR to bump the version in the next few days.

**Comment by mvdan** [comment]
What version bump do you mean? Note that the latest version, https://github.com/mvdan/gofumpt/releases/tag/v0.4.0, was already based on (and built with) Go 1.19.

The only quirk is https://github.com/mvdan/gofumpt/issues/244. If someone builds gofumpt with Go 1.18, its behavior changes, as we depend on the standard library's `go/printer` formatting behavior. We'll fix that, but it's unrelated to "bumping" the Go version.

**Comment by morremeyer** [comment]
I was looking at [the go.mod `go` line](https://github.com/mvdan/gofumpt/blob/3d971cbff40ecf22e0488b299a26fa66bb175604/go.mod#L3) and wrongly assumed this influenced anything.

I analyzed this further and discovered that this also happens when using `gofmt` (`cmd/gofmt`), so gofumpt is not the reason for this behaviour, it rather seems to be an issue in the code formatting that swag does or in gofmt itself.

I will continue to analyze this. If it's an issue in gofmt, I'll propose an update of that dependency one a fix has been made.

**Comment by morremeyer** [comment]
The issue was with my documentation, sorry for the fuzz here. Details in https://github.com/swaggo/swag/pull/1386#issuecomment-1359242144
