### ISSUE TITLE
Groups with comments below single var declaration are unexpectedly formatted

### ISSUE THREAD

**Issue by ndrpnt** [mvdan/gofumpt#256]
This is more of a question. The current behavior:
``` go
var (
	foo = "foo"
	// bar = "bar"
	// baz = "baz"
)
```
``` go
var foo = "foo" // bar = "bar"
// baz = "baz"
```
Is it desired ? I would expect `gofumpt` to either keep the parentheses and comments untouched, or to format this way:
``` go
var foo = "foo"
// bar = "bar"
// baz = "baz"
```
This is also consistent with the behavior when  adding an inline comment:
``` go
var (
	foo = "foo" // foo
	// bar = "bar"
	// baz = "baz"
)
```
``` go
var foo = "foo" // foo
// bar = "bar"
// baz = "baz"
```

I have no strong opinion on the matter, I just found it surprising. Feel free to close if this is intended

**Comment by mvdan** [comment]
The grouping seems right, even if it looks off - the commens are just comments, so they aren't considered as declarations. And a lone grouped declaration loses the grouping as it's overkill.

In your first example, `// bar = "bar"` should not become an inline comment, though. That's a bug.
