### ISSUE TITLE
Provide pre-commit hook configuration

### ISSUE THREAD

**Issue by trallnag** [mvdan/gofumpt#258]
[Pre-commit](https://pre-commit.com/) is a framework for managing and maintaining multi-language pre-commit hooks. People use it for example to format their code automatically on every commit.

It would be great if this repository could provide a configuration for it similar to how golangci-lint and other repos do it:

https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml

The alternative is to mirror this repository and include the `.pre-commit-hooks.yaml` file there.

**Comment by trallnag** [comment]
I have created a mirror of gofumpt that includes [`.pre-commit-hooks.yaml`](https://github.com/trallnag/pre-commit-mirror-gofumpt/blob/master/.pre-commit-hooks.yaml).

https://github.com/trallnag/pre-commit-mirror-gofumpt

**Comment by mvdan** [comment]
I'm not sure what happened on January 24th, but someone made a very similar suggestion in another project of mine: https://github.com/mvdan/sh/pull/966

My response is the same, given that both Go programs are equally easy to run on their own.

**Comment by trallnag** [comment]
Pre-commit added bootstrapping of Go if Go is not already installed. That's probably why.

But as gofumpt would only ever be used in Go projects this is not a real benefit. Except maybe the support for this new https://pre-commit.ci service that does not have Go preinstalled.

Thanks for the response
