### ISSUE TITLE
Document WHEN generated code is touched and how to mitigate it

### ISSUE THREAD

**Issue by 6543** [mvdan/gofumpt#265]
as #71 implemented by  #150 ... it should ignore generated code.

but it does not at woodpecker codebase.

to reproduce:
1. clone https://github.com/woodpecker-ci/woodpecker and checkout at e.g. at `56e66393`
2. `make format` to use gofumpt
3. `git diff` should not show changed files but it does :(

**Comment by 6543** [comment]
solved by https://github.com/woodpecker-ci/woodpecker/pull/1654

**Comment by mvdan** [comment]
The README says:

> Note that vendor directories are skipped unless given as explicit arguments.
> Similarly, the added rules do not apply to generated Go files unless they are
> given as explicit arguments.

You were using `find` to feed filenames explicitly to the tool, so these "skip" rules weren't kicking in. The change you applied is correct; you should generally be running gofumpt on the top-level directory to format everything.
