### ISSUE TITLE
gofumpt badge

### ISSUE THREAD

**Issue by codeallthethingz** [mvdan/gofumpt#266]
I'd like to add a badge to my project that says it proudly uses gofumpt.  ❤️ 

I created this one on shields.io but will copy pasta from your readme if you decide on including one.

[![code formatter: gofumpt](https://img.shields.io/badge/formatter-gofumpt-orange?style=flat-square&logo=go)](https://github.com/mvdan/gofumpt)

```
[![code formatter: gofumpt](https://img.shields.io/badge/formatter-gofumpt-orange?style=flat-square&logo=go)](https://github.com/mvdan/gofumpt)
```

**Comment by mvdan** [comment]
Hi, thank you for your sponsorship and your support!

Formatting is still relatively controversial, even in Go, so I think that proudly announcing formatting choices might not be  something we want to encourage :) Perfectly fine for each project to make their choice, though, of course.
