### ISSUE TITLE
Rewriting one element const blocks breaks godoc comments

### ISSUE THREAD

**Issue by twpayne** [mvdan/gofumpt#27]
`gofumpt` re-writes documented one-line top level `const` and `var` blocks to a single line. This is not correct if the block in documented. Consider:

```go
// Some foos.
const (
    Foo = 1
)
```

`gofumpt` re-writes this to:

```go
// Some foos.

const Foo = 1.
```

This detaches the comment from the declaration, causing `golint` to complain that `Foo` is not documented, whereas it was documented before `gofumpt` reformatted it.

As the comment cannot be written, I think the only option is to not reformat such blocks.

**Comment by mvdan** [comment]
Duplicate of #23? This very bug should have been fixed in master for a few days.

**Comment by twpayne** [comment]
Indeed a duplicate, many thanks!
