### ISSUE TITLE
No empty lines before a simple error check not working

### ISSUE THREAD

**Issue by ftamhar** [mvdan/gofumpt#271]
If my code like this
```go
package main

import "fmt"

func main() {
	var i int
	var err error
	i, err = fmt.Println("hello world")

	if err != nil {
		panic(err)
	}

	fmt.Println(i, err)
}

```

and I run `gofumpt -l -w .`, my expected result is like this
```go
package main

import "fmt"

func main() {
	var i int
	var err error
	i, err = fmt.Println("hello world"
	if err != nil {
		panic(err)
	}

	fmt.Println(i, err)
}
```

but the result is like the first code snippet.

How do I achieve the results I expect?

**Comment by flan6** [comment]
I noticed that sometimes it does not work too.

**Comment by mvdan** [comment]
This check only triggers if the previous line follows the `, err :=` pattern - note how it requires the token `:=`, it doesn't accept `=`. I agree that that's an unnecessary restriction, and we should make the formatter slightly more aggressive.
