### ISSUE TITLE
Tracking issue: go release tag fails semver version check

### ISSUE THREAD

**Issue by flowchartsman** [mvdan/gofumpt#280]
I created an issue that ended up as golang/go#61692, which involved RC version numbers failing gofumpt's semver check when attempting to determine minimal go version. This issue was [resolved](https://go.dev/cl/514815) from the `gopls` side by massaging the version number before passing to gofumpt, and the issue was closed, however it was unclear from the discussion whether @mvdan would want to make doc or code modifications to gofumpt as a result, and I didn't find any followup from @findleyr on putative updates to `x/mod` so I thought I'd open this issue so the discussion didn't get lost.

Feel free to close if unnecessary!

**Comment by mvdan** [comment]
Thanks for filing this - indeed it's on my mind, and we should have a tracking issue here.

I've raised https://github.com/golang/go/issues/62039 to properly track the upstream feature request.

**Comment by findleyr** [comment]
Thanks both. Indeed, I hadn't gotten around to filing an issue, and appreciate your tracking this.
