### ISSUE TITLE
Members of struct after Pass-through type inside struct's formatting is ignored

### ISSUE THREAD

**Issue by apprehensions** [mvdan/gofumpt#282]
This Go snippet (couldn't think of a better name):
```go
type Vocalization string

type Feline struct {
	MeowMeowMrrp string
	Miaow Vocalization
	Vocalization
}
```
works fine, as gofumpt formats it as so:
```go
type Feline struct {
	MeowMeowMrrp string
	Miaow        Vocalization
	Vocalization
}
```
however if the struct's order is like so:
```go
type Feline struct {
	MeowMeowMrrp string
	Vocalization
	Miaow Vocalization
}
```
it will remain as is. Is this intentional? or because of the passthrough struct not having a name inside the struct, gofumpt cannot calculate the formatting width?

**Comment by apprehensions** [comment]
Also, shouldn't the struct members be organized? organizing them may save memory.

**Comment by mvdan** [comment]
> it will remain as is. Is this intentional?

This is a formatting choice by gofmt. gofumpt will never fight gofmt on its formatting choices, per the README. I believe gofmt "breaks" vertical alignment in this case on purpose.

> Also, shouldn't the struct members be organized? organizing them may save memory.

gofumpt is a formatting tool, that has nothing to do with formatting. Plus, reordering struct fields can be a breaking change and should never be done automatically.
