### ISSUE TITLE
Put short case lists on a single line

### ISSUE THREAD

**Issue by josharian** [mvdan/gofumpt#3]
I’d love something like

https://go-review.googlesource.com/c/go/+/7593

and

https://go-review.googlesource.com/8050

But a bit more aggressive. I’ve been manually cleaning up excessive vertical whitespace in the compile for years because people were nervous about it.

**Comment by mvdan** [comment]
@josharian could you expand a bit on "short"? For example, case lists that fit in a single line of less than 40 or 60 characters?

Also, do you know of any other cases where gofmt collapses many lines into one? I can't think of one off the top of my head.

**Comment by josharian** [comment]
> could you expand a bit on "short"?

What does "long" mean in https://github.com/mvdan/gofumpt/issues/2?

gofumpt is still an experimental tool. I say we pick something, conservative if you prefer, and then iterate on it when we find false negatives and/or false positives.

> Also, do you know of any other cases where gofmt collapses many lines into one?

Nope.

**Comment by mvdan** [comment]
> I say we pick something, conservative if you prefer, and then iterate on it when we find false negatives and/or false positives.

Agreed; that's been my approach so far in #2. I was only asking in case you had a better idea in mind :)

**Comment by josharian** [comment]
yay, thanks!
