### ISSUE TITLE
Publish v1

### ISSUE THREAD

**Issue by silverwind** [mvdan/gofumpt#303]
Any reason why this tool is still at v0? It's widely used so I would recommend going to v1 to show that some stability guarantees can be given.

**Comment by mvdan** [comment]
Maybe at some point but not right now. The CLI is mostly stable, but the Go API and the features are in flux. See for instance https://github.com/mvdan/gofumpt/issues/78 or https://github.com/mvdan/gofumpt/issues/2.

**Comment by silverwind** [comment]
Ok, I hope it's still a goal to have v1 eventually. I really despise go packages that stay forever at v0 😆.
