### ISSUE TITLE
Import grouping vs internal

### ISSUE THREAD

**Issue by kolyshkin** [mvdan/gofumpt#307]
When working on the code in https://github.com/golang/go, gofumpt insists on placing imports of packages with `internal/` prefix to a separate group. Here's an example:

```diff
diff --git a/src/os/os_test.go b/src/os/os_test.go
index 9519aa0fc6..01f7932e4f 100644
--- a/src/os/os_test.go
+++ b/src/os/os_test.go
@@ -9,7 +9,6 @@ import (
        "errors"
        "flag"
        "fmt"
-       "internal/testenv"
        "io"
        "io/fs"
        "log"
@@ -26,6 +25,8 @@ import (
        "testing"
        "testing/fstest"
        "time"
+
+       "internal/testenv"
 )
```

@ianlancetaylor mentioned that this is not how they want their code to be formatted.

If this is by design, please close.

**Comment by ianlancetaylor** [comment]
Note that this is a special case for the Go standard library only.

**Comment by mvdan** [comment]
Thanks for the report. I added logic to treat `test/` and `example/` import path prefixes as non-std when https://github.com/golang/go/issues/37641 was proposed, and for some reason, I also did `internal/` prefixes then, with the comment that "they are unreachable". I'm not sure what I meant back then, but it doesn't make sense to me now :)

Indeed, std does contain some top-level internal packages, and they are still part of std, even if third party Go modules cannot import them directly. Will fix shortly.

**Comment by kolyshkin** [comment]
Thank you @mvdan; can we please have v0.6.1? 🙏🏻

**Comment by mvdan** [comment]
I'll do a v0.7.0 just before Go 1.23 is out, syncing with cmd/gofmt as well.

**Comment by kolyshkin** [comment]
> I'll do a v0.7.0 just before Go 1.23 is out, syncing with cmd/gofmt as well.

@mvdan very please 🙏🏻
