### ISSUE TITLE
octal notation with people misusing date.Time

### ISSUE THREAD

**Issue by ccoVeille** [mvdan/gofumpt#309]
I'm often facing the following pattern when using gofumpt

People are using time.Date with leading 0 for days, months, hours, minutes, or seconds …

here is an example
```go
        now := time.Date(2001, 02, 03, 04, 05, 06, 07, time.UTC)
```

A leading 0 is one of the octal notation

So gofumpt suggests fixing it to use the `0o` literal octal notation

So it transforms this piece of code into

```go
        now := time.Date(2001, 0o2, 0o3, 0o4, 0o5, 0o6, 0o7, time.UTC)
```

This pattern is very frequent.

https://github.com/search?q=+%22time.Date%2820%22+language%3Ago+%22%2C+02%2C+%22++&type=code&p=1

**Comment by ccoVeille** [comment]
I'm reporting the issue here as gofumpt is the tool that helped me to spot this misusage.

I would like to discuss here about the possible option we could have:
- update gofumpt code to add an exception for this
- add a rule to go-tools (style check maybe)
- add a linter to revive

What you guys think about it ?
cc @dominikh @mgechev @mvdan

**Comment by ccoVeille** [comment]
For records, I found examples of code where I'm sure gofumpt suggestions were applied, and where time.Date is now using the octal notation

https://github.com/search?q=+%22time.Date%2820%22+language%3Ago+%22%2C+0o1%2C+%22++&type=code

https://github.com/search?q=+%22time.Date%2820%22+language%3Ago+%22%2C+0o2%2C+%22++&type=code

https://github.com/search?q=+%22time.Date%2820%22+language%3Ago+%22%2C+0o4%2C+%22++&type=code

**Comment by mvdan** [comment]
gofumpt is a formatter, not a linter that spots bugs or rewrites your programs to try to fix bugs. The change that gofumpt made above is correct and the behavior of the code remains intact.

In your messages above you only suggested one change in gofumpt:

> update gofumpt code to add an exception for this (to remove the leading 0)

This is not a formatting change, so it is not something that gofumpt should ever do. If the user wrote an octal number, it is not gofumpt's job to rewrite the number to be decimal, even if the numeric value remains the same.

**Comment by dominikh** [comment]
This would be very similar to https://staticcheck.dev/docs/checks/#SA9002, just in the opposite direction.

**Comment by ccoVeille** [comment]
> This is not a formatting change, so it is not something that gofumpt should ever do.

Thanks @mvdan 

I was expecting such reply and I'm OK.

As I said, I reported it in the tool that helped me to spot the issue.

I was expecting to get feedbacks from everyone.

So I'm fine why you closing the issue in gofumpt

> This would be very similar to https://staticcheck.dev/docs/checks/#SA9002, just in the opposite direction.

Thanks @dominikh for confirming me static check is s good candidate. I will open a issue referencing this issue
