### ISSUE TITLE
Remove blank line after switch start

### ISSUE THREAD

**Issue by Kunde21** [mvdan/gofumpt#39]
An empty line between the switch statement start and the first case statement is similar the blank line after function/method declaration, not useful.  An empty line before the switch  can separate the whole block if needed, but after separates the code block awkwardly.   

Standardizing on the format:
```go
switch {
case x:
```
makes for a more coherent code block.

**Comment by mvdan** [comment]
Agreed. We should just treat the "switch block" like any other block, and forbid leading/trailing empty lines.

**Comment by mvdan** [comment]
Hm. We do already treat switch blocks like any other block.

We don't remove leading and trailing empty lines from all blocks, though - it's only when there is a single statement in the block. This translates to "a single case" when it comes to switches.

I think that's good enough. I think forbidding all leading and trailing lines in switch blocks could be annoying to those who prefer the extra spacing around switch cases. And after all, we allow it in other kinds of blocks.

Thoughts?

**Comment by Kunde21** [comment]
Maybe we can standardize the whole switch.  If cases aren't space separated, remove any space at the top.  Alternately, spaces between -> ensure space before.  The problem there comes when the cases aren't all formatted the same.  Not sure what we do there.

**Comment by mvdan** [comment]
That's a good point. We need to decide what "space separated cases" means, though. Is it:

```
switch foo {

case "a":
    sts()

case "b":
    sts()

}
```

Or:

```
```
switch foo {
case "a":
    sts()

case "b":
    sts()
}
```

I lean towards the latter, but if `case "a"` were super complex, I get that some might prefer a newline right before.

**Comment by ghazninattarshah** [comment]
Switch should be treated as for/if block not as a function block. I like the later one @mvdan mentioned no space after the switch, but empty line in between the following case statements.

**Comment by mvdan** [comment]
I still don't have a good answer to what we should do if some cases are separated, but others are not. Perhaps the developer meant to group some cases together, separate from others, for some reason. I've seen this in very large type switches in packages like go/ast and go/printer.

So I don't think we can reasonably implement a feature like this one, I'm afraid. We can't know if inconsistent spacing is an accident or meaningful and intentional.
