### ISSUE TITLE
don't add spaces to comments if any of the lines shouldn't have a comment

### ISSUE THREAD

**Issue by mvdan** [mvdan/gofumpt#43]
Right now, we decide if one single comment line is definitely not plain English given its first character, and then decide not to add a space prefix to it.

If that's the case, the same should apply to its whole "paragraph", i.e. the consecutive comment lines (before or after) which aren't empty.

**Comment by karel-3d** [comment]
This seems to break other case. I have a code like this, which is not formatted.

```go
package main

type MyType struct {
        // Foo is foo
        //bar baz
        Foo int
}
```

This is actually what https://github.com/gunk/gunk returns. When you have a gunkfile like this (note that here the comment space is *correct*)

```
package gunkexp

type MyType struct {
	// Foo is foo
	// bar baz
	Foo int `pb:"1"`
}
```

the resulting all.pb.go file looks like (omitting most of the result)

```
type MyType struct {
        // Foo is foo
        //bar baz
        Foo                  int32    `protobuf:"varint,1,opt,name=Foo,proto3" json:"Foo,omitempty"`
        XXX_NoUnkeyedLiteral struct{} `json:"-"`
        XXX_unrecognized     []byte   `json:"-"`
        XXX_sizecache        int32    `json:"-"`
}
```

and gofumpt does not format that back

**Comment by karel-3d** [comment]
I will make sure if it's really caused by this commit :)

**Comment by karel-3d** [comment]
yep it is
