### ISSUE TITLE
std imports must be in a separate group at the top is broken

### ISSUE THREAD

**Issue by ksegun** [mvdan/gofumpt#45]
The following import group
```
import (
	_ "expvar" // metrics
	"net/http"
	"net/http/pprof"

	"github.com/gorilla/mux"
)
```

is now being reordered as

```
import (
	"net/http"
	"net/http/pprof"

         _ "expvar" // metrics

	"github.com/gorilla/mux"
)
```

breaking our linter 

```
./pkg/metrics/metrics.go: Import groups are not in the proper order: ["Std" "Std" "Third party"]
```

**Comment by mvdan** [comment]
Sorry, what linter is that?

But yes, this was an unintended side effect. Will look into it.

**Comment by ksegun** [comment]
We understand and find your tool very valuable for our team so thank you for the work you do. 
We use [impi](https://github.com/pavius/impi/) to enforce the import grouping on our teams.

**Comment by mvdan** [comment]
Thanks, that's useful. While this isn't fixed, please just use an earlier version of master.

**Comment by russ-blaisdell** [comment]
We trust the tools we use to deliver a reliable master.  We are willing to accept our trust has been misplaced but not without a fight.

**Comment by ksegun** [comment]
Thanks for the quick turn-around!  💯
