### ISSUE TITLE
comments in import block

### ISSUE THREAD

**Issue by bgehman** [mvdan/gofumpt#46]
Shouldn't rewrite comments in import block.  Example:

**test.go**
```go
package test
  
import (
        "crypto/hmac"
        // #nosec
        "crypto/md5"
        // #nosec
        "crypto/sha1"
        "encoding/base64"
)
```

Results in (`$ gofumpt -s -w test.go`):
```
package test

import (
	"crypto/hmac"
	"crypto/md5"
	"crypto/sha1"
	"encoding/base64"

	// #nosec

	// #nosec

)
```

The `// #nosec` comments shouldn't be moved around (need for [gosec](https://github.com/securego/gosec)).  This linter is conflicting with [impi](https://github.com/pavius/impi/issues/9) -- can't make them them both happy at the same time.

**Comment by mvdan** [comment]
Thanks, this is indeed a bug.
