### ISSUE TITLE
Another comment spacing edgecase

### ISSUE THREAD

**Issue by karel-3d** [mvdan/gofumpt#52]
This is real edgecase from our repo

```
// BankCredential is (...)
//require (...) seperated by the
//'type' field.
```

This is not spaced, because gofumpt still thinks it's code (because the third line starts with `'`).

**Comment by karel-3d** [comment]
It should probably be solved in `gunk` rather than here, but can be solved here too

**Comment by mvdan** [comment]
Yeah, I think this would be too aggressive to do here. We should only space comments when we're pretty sure they aren't code, and a comment starting with a quote character is too ambiguous.
