### ISSUE TITLE
gofumpt returns different results when run multiple times

### ISSUE THREAD

**Issue by karel-3d** [mvdan/gofumpt#56]
A bit bizare bug.

I have this file (with tabs)

```
package main

import (
        "os"

        "io"
)
```

When I run `gofumpt -w foo.go`, I get

```
package main

import (
        "os"
        "io"
)
```

and when I run for a second time, I get

```
package main

import (
        "io"
        "os"
)
```

The tests did not catch this, since in the testscripts, there is always

```
gofumpt -w foo.go .
```

which actually visits the file *twice*, once as a `foo.go` and a second time when traversing the directory `.`.

A simple hacky fix is to format each file twice.

**Comment by karel-3d** [comment]
Oh, it's actually simple

it's because `ast.SortImports(fileSet, file)` is run *before* `internal.Gofumpt(fileSet, file)`, which puts the imports together

**Comment by mvdan** [comment]
> gofumpt -w foo.go .

Whoops, that's a mistake.

Yes, gofumpt should always be idempotent. It shouldn't generate changes more than once. I'll take a look later if you don't beat me to it.
