### ISSUE TITLE
gofumpt puts comment at end of imports when sorting imports

### ISSUE THREAD

**Issue by karel-3d** [mvdan/gofumpt#58]
Input

```
package main


import (
        "os" // comment to OS

        "fmt"
)
```

Expected: Either leave input as-is, or 
```
package main


import (
        "fmt"
        "os" // comment to OS
)
```

Actual output (with #57; without it, fmt and os are switched, but comment still below):

```
package main

import (
        "fmt"
        "os"
        // comment to OS
)
```

I hit this issue when trying testcases for #55 (without the option)

**Comment by mvdan** [comment]
Duplicate of #46?

**Comment by karel-3d** [comment]
Yes, seems similar. (Comments are not below but on the right, but in general the same problem)

Closing as duplicate
