### ISSUE TITLE
wishlist: ensure at least one-space between comment `//` and next character

### ISSUE THREAD

**Issue by dnwe** [mvdan/gofumpt#6]
i.e.,
```go
//This does that...
```
becomes
```go
// This does that...
```

**Comment by dnwe** [comment]
tbh even that I would consider a useful feature because when I review the `git diff` output it would highlight wherever I have accidentally left some commented out code that should be deleted :)

**Comment by mvdan** [comment]
Note to self - be careful with line directives, such as `//go:generate`, `//+build`, and `//line`. If people use custom directives that we don't know about, this could end badly.

**Comment by mvdan** [comment]
Oh, the files containing `//+build` are buggy, actually. That should be `// +build`.

**Comment by mvdan** [comment]
Done; any feedback welcome.

**Comment by dnwe** [comment]
😘👌🏻 has worked well on the repos I've tested so far. Thank you!

Having also tried it across a number of OSS repos, one minor tweak might be to consider `//` followed by one or more additional non-alphanumerical characters (e.g., `/`, `*`, `+`, `-`) as likely to be block comments of a particular "style" intended to separate sections of code or for a Copyright header or something

e.g.,
https://github.com/Shopify/sarama/blob/5d2af84cf5e2dd36f2daecaaafa13c4e286f20fd/mocks/consumer.go#L37-L46

**Comment by mvdan** [comment]
Thanks; that's a good idea. I'll update the rule to be a bit more conservative.

**Comment by sylr** [comment]
I make a great distinction between:

A comment:
```go
// This is a comment
if thisiscommentedcode == false {

}
```

And commented code:
```go
//// This is a comment
//if thisiscommentedcode == false {
//
//}
```

**Comment by mvdan** [comment]
@sylr are you bringing this up because gofumpt isn't doing what you think it should? If so, please raise a new issue.
