### ISSUE TITLE
Ensure new line is added after if statement

### ISSUE THREAD

**Issue by rhzs** [mvdan/gofumpt#60]
IMHO, it would be better if we can ensure new line creation after `if` parentheses, but this shouldn't be added if the `if` statement doesn't have continuity / codes.

No new line is added
```go
func main() {
     if true {
        // logic
     }  
} // no new line
```

New line is added to separate `if`
```go
func main() {
     if x == 5 {
        // logic
     }  
    // <---   Here new line is automatically added, to separate if logic
    x = 10
} // no new line
```

I hope it won't be too aggressive and can be switched off if the user doesn't want it.

**Comment by mvdan** [comment]
I honestly disagree. For example, imagine:

```
param := "default"
if someSetting {
    param = "other"
}
callFunc(param)
```

I think this is entirely reasonable. There's just no way for us to know when the "chunks of logic" start and end. This should be left up to the developer. Some users prefer more empty lines than others, too.

We already have a few extra rules to add or remove empty lines, but they are for cases that are pretty evident. I'm happy to extend those rules, but this seems far too subjective.

**Comment by rhzs** [comment]
Hi @mvdan thanks for sharing your views and perspective.
After thinking it for a while, I agree with you. It is just a preference and too opinionated.
