### ISSUE TITLE
Best way to avoid generated files?

### ISSUE THREAD

**Issue by gonzaloserrano** [mvdan/gofumpt#61]
Hey Daniel,

We've got some protos, graphql stuff, json schema and moq generated files with the canonical generated header https://github.com/golang/go/issues/13560#issuecomment-288457920 and I'd like to not apply gofumpt to those for CI purposes.

I could try with some `find` + `grep` but maybe you have something better under your hat?

Thanks!

**Comment by mvdan** [comment]
Usually one would teach the generators to generate output that follows `gofmt`. Try the same with `gofumpt`?

An alternative, for third party generators that you don't want to modify, is something like:

```
//go:generate sometool -o out.go
//go:generate gofumpt -w out.go
```

The current tool doesn't differentiate generated files from non-generated ones, just like gofmt and goimports don't. I guess we could add that, but it feels unnecessary.

**Comment by gonzaloserrano** [comment]
Ok thank you 👍
