### ISSUE TITLE
breaking long lines with lots of arguments

### ISSUE THREAD

**Issue by karel-3d** [mvdan/gofumpt#64]
Is there an interest in implementing breaking long lines into multiple lines?

For example, if there is this line in code

```
	if err := chromedp.Run(ctx, tasks.ExtractAccountDataFromDropdown(&accountTypeStr, &name, &accountNo, &currency, &balance, idx)); err != nil {
```

which is 146 chars long (with the first tab), break it into

```
	if err := chromedp.Run(
		ctx,
		tasks.ExtractAccountDataFromDropdown(&accountTypeStr, &name, &accountNo, &currency, &balance, idx),
	); err != nil {
```

or even into

```
	if err := chromedp.Run(
		ctx,
		tasks.ExtractAccountDataFromDropdown(
			&accountTypeStr,
			&name,
			&accountNo,
			&currency,
			&balance,
			idx,
		),
	); err != nil {
```

I might look into that as an exercise, but I am not sure if there is interest in it :)

the same logic with long function definitions, of course

**Comment by mvdan** [comment]
Sure - you can give your thumbs up to #2 :)
