### ISSUE TITLE
pick up go version from go.mod file in go modules

### ISSUE THREAD

**Issue by twpayne** [mvdan/gofumpt#67]
As [discussed](https://github.com/mvdan/gofumpt/issues/51#issuecomment-623001599) in #51, `gofumpt` should pick up the Go version from a module's `go.mod` file so it can apply formatting that is specific to a range of Go version.

**Comment by mvdan** [comment]
Right now, this is hard-coded to Go 1.15, the current "latest" language version.

**Comment by mvdan** [comment]
This was done in 42bb51311e31092b352bf753ea246ec904c6d4d5, I forgot to link this issue :)
