### ISSUE TITLE
consider golangci-lint integration?

### ISSUE THREAD

**Issue by twpayne** [mvdan/gofumpt#69]
[`github.com/golangci/golangci-lint`](https://github.com/golangci/golangci-lint) includes a `gofmt` linter that verifies that code is formatted with `gofmt` ([code](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/gofmt.go)).

Would you consider a similar integration for `gofumpt` into `golangci-lint`?

Note that this would address some of #28 by association as fixed versions of `gofumpt` would be bundled inside `golangci-lint` releases.

**Comment by mvdan** [comment]
Sure, why not - but wouldn't that be work on their end? If you're asking about making my code available, note that it's already exposed via https://pkg.go.dev/mvdan.cc/gofumpt/format as of a few days ago.

**Comment by gonzaloserrano** [comment]
It has just been merged https://github.com/golangci/golangci-lint/pull/1177

**Comment by mvdan** [comment]
Great - I'll consider this done :)
