### ISSUE TITLE
Support for staticcheck's //lint:ignore directives

### ISSUE THREAD

**Issue by fsouza** [mvdan/gofumpt#7]
Currently, gofumpt adds a space after ``//`` and that causes staticcheck to not recognize the directive.

**Comment by dominikh** [comment]
:-(

**Comment by mvdan** [comment]
Thanks - there were more directives than I thought. It doesn't help that there isn't really one standard syntax for them. I'll make the rule less agressive, but probably tomorrow as I need to sleep.

**Comment by mvdan** [comment]
I've made the solution somewhat generic, so other `//foo:bar` directives should be left alone too.
