### ISSUE TITLE
force multiline function signatures to separate the body

### ISSUE THREAD

**Issue by mvdan** [mvdan/gofumpt#73]
That is, turn

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7) {
    doWork(...)
}
```

into the more readable:

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7,
) {
    doWork(...)
}
```

This is important to properly separate the parameter list from the function body, since in the first case they share the same indentation level.

I've seen an empty line be used for this too, as seen below, but it takes the same amount of lines and it's less clear and consistent:

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7) {

    doWork(...)
}
```

This rule could be made stronger in the future, such as enforcing parameters to all be on separate lines, but I don't want to go that far right now. I assume most Go developers would not have an issue with this smaller change.

cc @twpayne @rogpeppe @kovetskiy @Southclaws @geoah for input

**Comment by geoah** [comment]
I think this is a good start indeed, thank you @mvdan 

```func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7,
) {
    doWork(...)
}```

**Comment by kovetskiy** [comment]
The only thing that we want to avoid is to make it even less readable, imagine we have a soft limit to 120 characters per line

```
func VeryLongAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(p T0, 
    param1 T1, param2 T3,
) {
    doWork(...)
}

```

Now you can see that `p T0` is on the first line and it's really easy to miss it.

What if gofumpt will force parameters on long lines always go on the next line?
```
func VeryLongAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(
    p T0, param1 T1, param2 T3,
) {
    doWork(...)
}
```

**Comment by mvdan** [comment]
@kovetskiy probably, but that feels like part of #2. This feature would not consider line length at all.

**Comment by csilvers** [comment]
> This rule could be made stronger in the future, such as enforcing parameters to all be on separate lines

I'm actually interested in writing such a lint-check for our own organization.  It would have the semantics that if a function's "first line" (receiver + name + parameter list + return) does not fit on one line, it requires it to be broken it up so that each parameter is on own line, and possibly each return value (and possibly the receiver) as well.  It would require, as input, a line-length limit.

Would there be interest in incorporating this into gfumpt (presumably opt-in) if I wrote it?  If so I might do it that way, rather than as a separate linter.

(I would write this error to be auto-fixable, if that's possible in gofumpt -- I don't know enough about the tool yet to say.  Our org would be using this as part of golangci-lint, which recently brought in gofumpt support, which is what led me here.)

**Comment by csilvers** [comment]
(Ah, I see now this is discussed at length in #2, so maybe it's premature to consider it for gofumpt at this time.)

**Comment by mvdan** [comment]
@csilvers breaking up long lines would be #2, yes. There is a WIP PR if you want to give it a try.

The rule here (and the potential follow-up you linked) would be based purely on consistency with newlines, not on line length limits. That being said, if we implement a rule like "if any parameter is in a separate line, all parameters are on separate lines", then #2 splitting the parameter list due to the line length limit could then cascade into that rule.

**Comment by mvdan** [comment]
I'm going to reopen this for now, because for the upcoming 0.2.0 release, we only implemented half of this proposed rule. This allows us to take incremental steps in a more conservative way, reducing the chance that we make the heuristics too aggressive too quickly and annoy users.

In particular, the rule is now:

> Functions using an empty line for readability should use a `) {` line instead

So, the following:

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7) {

    doWork(...)
}
```

turns into:

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7,
) {
    doWork(...)
}
```

The next step will be to also separate the `){` line on:

```
func VeryLong(param1 T1, param2 T2, [...],
    param6 T6, param7 T7) {
    doWork(...)
}
```
