### ISSUE TITLE
remove gofumports once gofumpt is part of gopls

### ISSUE THREAD

**Issue by mvdan** [mvdan/gofumpt#75]
As far as I know, the main reason to support a fork of goimports was because multiple editor integrations only allow running gofmt or goimports, not both at the same time. Thus, if one wanted to use gofumpt while also getting the benefits of goimports, gofumports was useful.

However, a lot has changed in the past year; gopls has come a long way, and most major editors have good gopls integrations by now. They will also add gofumpt soon: https://github.com/golang/go/issues/39805

So I see less reason to support a fork of goimports on top of a fork of gofmt. If someone really wants to get the best of both worlds from the command line, they can just run both tools one after the other, like: `goimports -l -w . && gofumpt -l -w .`

There are several advantages to dropping the goimports fork:

* goimports is big and complex, making this module very large (I have to copy a dozen internal packages)
* Given the point above, it's also extra work to maintain the project, especially in the long run
* goimports is not a superset of gofmt; for example, the `-s` flag does not exist there, and we want to start enforcing it
* Encouraging the use of a single formatter for all needs is a losing game - as long as gofumpt and goimports don't contradict each other, we are OK

Will leave this issue open for a couple of weeks to see what others think. I'll wait for the gopls issue to be fixed and released, in any case.

**Comment by dnwe** [comment]
@mvdan whilst I can see the motivation to discard it due to the maintanence burdon, the one obvious thing I'd miss, having enjoyed it for a while, is the std import coalescing (from https://github.com/mvdan/gofumpt/issues/8) as https://github.com/golang/go/issues/20818 hasn't had any movement.

**Comment by mvdan** [comment]
Oh, that would remain as part of gofumpt, just like it exists there today. All the extra rules we have apply to both tools equally, minus enforcing of the simplify `-s` flag, since that's missing from `goimports`.

**Comment by dnwe** [comment]
TIL — I thought I only had that because I was running gofumports on save :)

**Comment by mvdan** [comment]
I personally never use gofumports. It's only useful if you want both gofumpt and goimports at once, and can't run both tools separately. It's a pretty weird edge case :)
