### ISSUE TITLE
group all standard library imports

### ISSUE THREAD

**Issue by sonatard** [mvdan/gofumpt#8]
```go
import (
	"github.com/b/xxxx"
	"context"

	"time"

	"github.com/a/xxx"
)
```

I hope following code after gofumports.

```go
import (
	"context"
	"time"

	"github.com/a/xxx"
	"github.com/b/xxxx"
)
```

**Comment by mvdan** [comment]
Looks like this is being implemented in https://github.com/golang/go/issues/20818. Since it's planned there, and since implementing this would be non-trivial, let's wait and see how that issue progresses.

**Comment by mvdan** [comment]
Hmm, if I do this only for standard library imports, that might be simple enough to implement on our side.

**Comment by mvdan** [comment]
I took a shot at this yesterday, but it's a nightmare to implement properly while keeping good position information. That is, without messing up empty lines or comments.

**Comment by sonatard** [comment]
I think gofumports delete only empty lines in imports. exec goimports after gofumports.

1. gofumpotrs delete empty lines.
```go
import (
	"github.com/b/xxxx"
	"context"

	"time"

	"github.com/a/xxx"
)
```
```go
import (
	"github.com/b/xxxx"
	"context"
	"time"
	"github.com/a/xxx"
)
```

2. Exec goimports

```go
import (
	"context"
	"time"

	"github.com/a/xxx"
	"github.com/b/xxxx"
)
```

**Comment by mvdan** [comment]
While that's an interesting idea, it wouldn't work; we'd also be clumping together non-std imports. For example, a common standard is to group together third-party imports by project or by purpose.

**Comment by mvdan** [comment]
The heuristic here was a bit lax; I've made it a bit more aggressive. See the commit pushed to master just above.
