### ISSUE TITLE
breaking CGO compabitility

### ISSUE THREAD

**Issue by moul** [mvdan/gofumpt#86]
Hi,

I've this go file:

```go
// +build darwin

package mcdriver

/*
#cgo CFLAGS: -x objective-c
#cgo darwin LDFLAGS: -framework Foundation -framework MultipeerConnectivity
#include <stdlib.h>
#include "mc-driver.h"
*/
import "C"
import "unsafe"

[...]
```

Becoming like this (after running `go run mvdan.cc/gofumpt -w -s .`)

```go
// +build darwin

package mcdriver

/*
#cgo CFLAGS: -x objective-c
#cgo darwin LDFLAGS: -framework Foundation -framework MultipeerConnectivity
#include <stdlib.h>
#include "mc-driver.h"
*/
import (
        "C"
        "unsafe"
)

[...]
```

Which breaks the requirements needed to use CGO: https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command

---

I don't have the necessary knowledge to make a PR for this, sorry, but I would like to know if someone can help supporting CGO files?

Else, it would be nice to have a way of defining files to exclude, i.e. by detecting this `import "C"`, or manually by specifying an exclude list?

Thank you very much

**Comment by mvdan** [comment]
This sounds like a bug :) We should probably be treating `import "C"` as special, and not join it with the rest. We probably missed that detail while writing the code to organize imports.

If you'd like to work on a PR, it should be fairly simple. You'd just need to also write a couple of tests.

**Comment by moul** [comment]
@mvdan I gave a look at your codebase, and I can find that there is already some code related to exclude CGO imports -> https://github.com/mvdan/gofumpt/blob/master/gofumports/internal/imports/fix.go#L190-L209

I'm sorry, but I don't understand so much the structure of the repo, any advice to get started?

**Comment by mvdan** [comment]
That's just a copy of goimports, ignore all under gofumports. Our entire logic is in https://github.com/mvdan/gofumpt/blob/master/format/format.go.

The function that joins std imports is `https://github.com/mvdan/gofumpt/blob/ab5a8192947d6e9288319185f48cfbdcca057700/format/format.go#L534`. As you can see, it doesn't handle `"C"` any different. I think that making it skip that import might be enough.

**Comment by mvdan** [comment]
Upon closer inspection, my hint above was actually incorrect. `joinStdImports` only works with import "groups" within a single import declaration. The code that joins multiple import declarations into one is in a different place. That's probably why you got stuck trying to fix this, apologies.
