### ISSUE TITLE
don't remove empty line after a condition if it harms readability

### ISSUE THREAD

**Issue by Zamiell** [mvdan/gofumpt#88]
Greetings, and thanks for the excellent formatter.

As explained in the README.md file, gofumpt has the rule: "No empty lines around a lone statement (or comment) in a block".
e.g.

```
if err != nil {

	return err
}
```
```
if err != nil {
	return err
}
```

This is a sensible rule. However, it does not seem to account for multi-line conditionals. Consider the following:

```
// This return statement is intentionally spaced apart from the conditionals in order to strongly delineate
// the "if statement" and the "executing code block", so to speak
if longCondition1 &&
	longCondition2 &&
	longCondition3 &&
	longCondition4 &&
	longCondition5 {

	return 123
}
```
```
// gofumpt has now made the return statement smooshed together with the conditionals,
// making it hard to see, at a glance, which lines are if statement conditions, and which lines are executing code
if longCondition1 &&
	longCondition2 &&
	longCondition3 &&
	longCondition4 &&
	longCondition5 {
	return 123
}
```

I propose that gofumpt "leaves alone" this 2nd code snippet.
This would change the wording of the rule to something along the lines of:
"No empty lines around a lone statement (or comment) in a block (unless it is a multi-line conditional)".

**Comment by mvdan** [comment]
I agree. I generally try to avoid multi-line conditions, but on occasion I do use this formatting and I do keep a separate line.

Want to send a patch? It shouldn't be hard to implement, as it's just altering the existing logic by comparing the end line of the condition and the start line of the body.

**Comment by Zamiell** [comment]
I took a look at the source code and its a bit over my head, sorry.

**Comment by Zamiell** [comment]
Any updates on this?

**Comment by mvdan** [comment]
This is an open source side project that I do for free on my spare time. If you want me to work faster, consider [becoming a sponsor](https://github.com/sponsors/mvdan).

**Comment by Zamiell** [comment]
Thanks Daniel!
