### ISSUE TITLE
Add vim-go instructions for gofumports? 

### ISSUE THREAD

**Issue by kevinburkemeter** [mvdan/gofumpt#93]
Hi,
It would be nice if there were instructions on how to integrate gofumpt/gofumports with vim-go. Specifically we're trying to onboard team members who are getting mixed up by the Go issue where the imports aren't being grouped appropriately.

**Comment by mvdan** [comment]
People have contributed sections for specific editors and editor integrations already, so a PR would be welcome. I don't use vim-go, so I can't personally describe this.
