### ISSUE TITLE
deprecation notice on tip

### ISSUE THREAD

**Issue by kevinburkemeter** [mvdan/gofumpt#94]
Using the instructions at the top of the README with Go tip, I get this notice

```
$ GO111MODULE=on go get mvdan.cc/gofumpt

go: downloading mvdan.cc/gofumpt v0.0.0-20201123090407-3077abae40c0
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	See 'go help get' and 'go help install' for more information.
go get: added mvdan.cc/gofumpt v0.0.0-20201123090407-3077abae40c0
```

**Comment by mvdan** [comment]
I plan on recommending `go install mvdan.cc/gofumpt@latest` once Go 1.16 is out, but that won't be the case for two months yet.

Even then, it will be debatable to recommend that, because it won't work on 1.15. So for now, we have to stick to this `go get`.

**Comment by kevinburkemeter** [comment]
Eek, it's frustrating that there's no command that works with both versions.

**Comment by mvdan** [comment]
Well, the current `go get` line will work roughly between Go 1.12 and Go 1.16, at least. I don't think they'll break its behavior until at least 1.17, at which point we can fairly safely rely on everyone being able to use `go install <path>@latest`.

**Comment by mvdan** [comment]
There's not much I can do here, so instead I've raised https://github.com/golang/go/issues/42885. Closing in favor of that upstream issue.

**Comment by kevinburkemeter** [comment]
Thanks! You put a lot of care into that issue report and I appreciate it.
