### ISSUE TITLE
Empty Lines After Conditions Isn't Respected if there is a Comment

### ISSUE THREAD

**Issue by Zamiell** [mvdan/gofumpt#96]
Hello and happy Thanksgiving. 🦃 

`gofumpt` recently implemented the feature of leaving along the following code:

```
if longCondition1 &&
	longCondition2 &&
	longCondition3 &&
	longCondition4 &&
	longCondition5 {

	return 123
}
```

However, it seems that `gofumpt` will still mess up code with comments.
For example, the following code:

```
if longCondition1 &&
	longCondition2 &&
	longCondition3 &&
	longCondition4 &&
	longCondition5 {

	// We specifically want to return 123 here because of quantum fluctuations
	return 123
}
```

Will be transformed into:

```
if longCondition1 &&
	longCondition2 &&
	longCondition3 &&
	longCondition4 &&
	longCondition5 {
	// We specifically want to return 123 here because of quantum fluctuations
	return 123
}
```

This is undesired for the same reason as [the original issue](https://github.com/mvdan/gofumpt/issues/88).
Is this a bug?

**Comment by mvdan** [comment]
Yep, I agree this is a bug.

**Comment by mvdan** [comment]
@Zamiell can you provide a way to reproduce the bug? In isolation, I cannot:

```
$ cat /tmp/f.go
package p

func f() {
	if true &&
		true {

		// documented single statement
		println()
	}
}
$ gofumpt /tmp/f.go
package p

func f() {
	if true &&
		true {

		// documented single statement
		println()
	}
}
```

It's possible that another rule modified an earlier chunk of your program and somehow interacted with this rule. But I'd need a way to reproduce to be able to investigate.

**Comment by Zamiell** [comment]
Oh, I just realized that it is possible that I was using gofumpt as part of golintci-lint. Does that version have the feature in question?

**Comment by mvdan** [comment]
golangci-lint bundle a specific version of each tool, including gofumpt, so you should ask them and/or prompt them to update it. When filing bugs, you should check gofumpt directly.

**Comment by Zamiell** [comment]
Oops. Yeah, I verified that it works fine on the version from master, so this issue is noise.
Who is responsible for updating gofumpt on golangci-lint? I thought it was usually the creator of the tool.

**Comment by mvdan** [comment]
> Who is responsible for updating gofumpt on golangci-lint?

I have no idea, sorry. I'm certainly not involved :)
